dosemu2/dosemu2

src/base/init/config.c
src/base/init/lexer.l.in
src/base/init/parser.y.in
src/plugin/X/X.c

I forgot handling of the default case in X_vidmode() (non-fullscreen change).
Also, disallow ungrabbing keyboard unless we know it can be regrabbed (by EnterNotify event).  It's not easy to just restore window decorations temporarily because the fullscreen window is created with override_redirect.

Xrandr fullscreen

---

src/plugin/commands/msetenv.c

memcpy() is used with overlapping src and dest.  Use memmove() instead.  This
would corrupt the DOS environment when a var is being removed or replaced.

Fix an old bug corrupting the DOS env block.

---

src/plugin/X/X_keymaps.c
src/plugin/kbd_unicode/keymaps.c

1/ Simplified the detection to just check the plain and shifted keycodes, as
incorrect selections(UK) were being made due to no alt keys being available in
the plain X11 keymap data.
2/ Added the ability to use Xkb keyboard extension if available.
3/ Tweaked kernel console keymap access error message.
Tested both Xkb and plain X11 versions with:
a) UK primary and FR secondary -> uk, fr-latin
b) DE primary and US secondary -> de-latin, us

Keymap: Rework X11 detection

---

src/arch/linux/async/signal.c
src/arch/linux/async/sigsegv.c
src/base/dev/vga/vgaemu.c
src/base/misc/dump.c
src/base/video/instremu.c
src/doc/DANG/DANG.sgml
src/dosext/dpmi/dpmi.c
src/dosext/dpmi/dpmi.h
src/dosext/dpmi/msdos.c
src/dosext/dpmi/msdos.h
src/emu-i386/cpu.c
src/emu-i386/simx86/codegen-sim.c
src/emu-i386/simx86/codegen.h
src/emu-i386/simx86/cpatch.c
src/emu-i386/simx86/cpu-emu.c
src/emu-i386/simx86/emu86.h
src/emu-i386/simx86/memory.c
src/emu-i386/simx86/sigsegv.c
src/include/cpu-emu.h
src/include/cpu.h
src/include/emu.h
src/include/vgaemu.h
src/plugin/console/vc.c
src/plugin/term/terminal.c

Since kernel 2.1.1 the sigcontext structure has been named sigcontext. I
don't believe Dosemu2 will be built on anything earlier.

Rename sigcontext_struct references to sigcontext

---

src/plugin/commands/builtins.c

Older DOS version (3.0 -> 3.31) don't have a name field in MCB. The info
is available immediately following the environment strings. So if we
don't find the program using mcb->name then try again by constructing
one from argv[0] which was derived from the environment block. This allows
the Dosemu builtins to function on older DOSes. Potentially something
similar could be used to update the window title in X.

Builtins - old DOS get program name from the env

---

src/base/misc/fatfs.c
src/base/misc/fatfs.h

This series of patches [fixes #49] allow MS-DOS 3.3 to boot on both FAT12 and FAT16 filesystems generated by hdimage directory. For them to be operational the missing part is that somehow the filesystem size must be constrained to be recognisable by MS-DOS 3.3. For testing I patched disks.c
as follows:
For FAT16
```C
diff --git a/src/base/misc/disks.c b/src/base/misc/disks.c
index ef0baa2..1961b10 100644
--- a/src/base/misc/disks.c
+++ b/src/base/misc/disks.c
@@ -512,9 +512,9 @@ void dir_auto(struct disk *dp)
* We emulate an entire disk with 1 partition starting at t/h/s 0/1/1.
* You are free to change the geometry (e.g. to change the partition size).
*/
-    dp->sectors = 63;
-    dp->heads = 255;
-    dp->tracks = 255;
+    dp->sectors = 17;
+    dp->heads = 4;
+    dp->tracks = 605; …
```

MS-DOS 3.3 fatfs boot patches

---

src/base/misc/fatfs.c

I cleaned up the OS detection for newer MS-DOS versions and also fixed the detection of PC-DOS earlier than v3.30. I tested:
~~~
MS-DOS versions 3.20,3.21,3.30,4.01,5.00,6.00,6.20 and 6.22 which all boot.
I don't have v7.00 or greater so would appreciate it if you could check the 'MZ' support?
~~~
~~~
PC-DOS versions 3.00,3.10,3.20,3.30,5.00,6.10 and 7.00 which all now boot.
Version 4.00 is still failing, but is being detected correctly
~~~

Clean-up MS-DOS >= v7 detection and fix PC-DOS detection < v3.30

---

src/dosext/dpmi/msdos/segreg.c

This fixes Win 3.1 with the WinOS2 mouse driver and KVM.

Reset segment override before decoding instruction prefixes.

---

etc/dosemu.conf
etc/global.conf
src/base/init/lexer.l.in
src/base/init/parser.y.in
src/base/misc/disks.c
src/include/disks.h

This patch adds a config option that allows the user to choose a predetermined
disk type at runtime for hdimage that create a fatfs filesystem from a
directory. This is useful with older versions of DOS e.g. those before v4.0
that did not support large disks or FAT16B filesystems. The disk geometry
chosen is that used by the early IBM BIOS. This page details the types
available:
http://webpages.charter.net/danrollins/techhelp/0054.HTM
A new dosemu.conf variable '$_hdtype' is added with the default being
the current behaviour with keyword of "none", and the following types are
supported from that list
$_hdtype = "type1" # creates 10mb IBM type1 disks with C/H/S of 306/4/17
$_hdtype = "type2" # creates 21mb IBM type2 disks with C/H/S of 615/4/17

disks: Allow the user to force disk type at runtime

---

src/arch/linux/mapping/mapping.c
src/base/init/config.c
src/emu-i386/cpu.c
src/emu-i386/do_vm86.c
src/emu-i386/kvm.c
src/include/emu.h
src/include/kvm.h
src/include/mapping.h

This fixes cpu_vm="auto" if KVM is not available (because of kernel
CPU, or BIOS). The fallback code has been mostly consolidated into
cpu.c, and KVM functions are defined in a new header kvm.h.

Auto-detect KVM, and fall back to CPUEMU if not available.

---

src/tests/test-i386-code16.S
src/tests/test-i386.c

This is possible because the first 16 selector entries are reserved
for the "Allocate Specific LDT Descriptor" DPMI function.
The old way of using selectors 0x10f/0x117 no longer works because
DOSEMU now uses more selectors itself.

In CPU tests use the same selectors (0xf/0x17) for DJGPP as for Linux.

---

src/dosext/dpmi/msdos/msdos.c
src/include/cpu.h

While working on PR #114 I decided to test with Jazz Jackrabbit which did not work so I went on to fix that first.
Perhaps we should have a SEL_DOS_ADR_CLNT in dpmi.c to avoid needing to do DOSADDR_REL(MEM_BASE32(p))?
In the end I think dosaddr_t is the correct type for most things in msdos.c so a bigger cleanup would be to have SEL_ADR_CLNT return a dosaddr_t everywhere. It just means we can't use snprintf any more.
For now this is just the minimum to fix the rabbit game.

Jazz jackrabbit fixes

---

src/dosext/dpmi/dpmi.c
src/dosext/dpmi/dpmi.h
src/dosext/dpmi/memory.c

When working on the KVM DPMI patch I found it annoying to have so many DPMI mappings. Sometimes the locked pm stack would be below mem_base, sometimes above, etc.
I found it easiest to just combine everything into the pool memory. This way all DPMI memory is in a single block which also makes debugging easier.
To keep the handle number the same for DPMI clients, there is a private host_pm_block_root for the pmstacks, data & code helpers and LDT alias memory.

 Dpmi use pool mem only

---

src/base/misc/fatfs.c

The filenames for older DR-DOS (3.40/3.41) were incorrect.

Fatfs: Fix the bootfile names for early DR-DOS

---

src/arch/linux/async/signal.c
src/arch/linux/async/sigsegv.c
src/emu.c
src/include/sig.h

These three patches eliminate 3 syscalls in fault handlers, which saves about 15% per fault here on x86_64 (from 2.2 to 1.85 microseconds for sti in dpmi).

Fault speedups

---

src/arch/linux/mapping/mapping.c
src/base/init/init.c
src/dosext/dpmi/dmemory.h
src/dosext/dpmi/memory.c

The only time this is not possible is when using vm86() on i386,
of if $_dpmi is explicitly set by the user.
Making the space contiguous avoids looking for VMAs under 1G and
simplifies the KVM-DPMI patch.

mapping: allocate contiguous memory for low + dpmi when possible.

---

autogen.sh
configure.ac
mkpluginhooks
src/Makefile.common
src/dosext/dpmi/Makefile
src/dosext/dpmi/msdos/Makefile
src/plugin/X/Makefile

For dosemu1 I had one out-of-tree build for i386 and one for x86_64 and that is not working any more.
This fixes it.

build system: re-enable out-of-tree builds

---

src/commands/Makefile
src/plugin/commands/Makefile

This partly reverts 0a5f8922ace6e. The problem with using ld
directly is that it breaks "target_bits 64" when (cross-)compiling
with i386 userspace, as the "-m64" is lost.
Of course this is not the only way to fix this issue, one can also add "-m elf_i386" or "-m elf_x86_64" to the ld command line but that needs a bit more setup.

build system: link DOS binaries indirectly with GCC

---

src/emu-i386/simx86/sigsegv.c

This helps Prehistorik 2 a little bit (bug #104).

simx86: fix _rip in scas/cmps handler for JIT accesses to vgaemu mem.

---

src/base/dev/vga/vgaemu.c
src/base/video/text.c

This fixes the first intro screen for Prehistorik 2 (#104).
vga.line_compare was already used for graphics modes. For text
mode this meant replacing all
"- vga.display_start" to calls to memoffs_to_location()
"+ vga.display_start" to calls to location_to_memoffs()
which take care of line compares, and adjusting memcpy, memcmp,
and selection code.

vgaemu: use vga.line_compare for split screen in text mode.

---

src/base/misc/fatfs.c

DR-DOS has boot files that follow three different naming conventions:
1/ DRBIOS.SYS, DRBDOS.SYS - Old DR-DOS < v5.0
2/ IBMBIO.COM, IBMDOS.COM - IBM compatible names v5.0 -> v8.0
3/ DRBIO.SYS, DRDOS.SYS   - Enhanced DR-DOS (http://drdosprojects.de)
Since some variants share filenames with PC-DOS, the logic may fail due to the
file sizes not matching those expected for version detection. This patch
adds:
1/ a new case for (2) which will now boot DR-DOS v5.0 to 8.0 [fixes #151]
2/ a new case for (3) which is currently just a placeholder

fatfs: Refine detection logic for DR-DOS variants

---

src/base/misc/disks.c

These trivial patches aim to make the debug logging for disks more consistent between plain int 13h reads and the extended variant in order to aid comparison of logs generated from a vbootfloppy boot and a hdimage boot.

Boot cleanups 02

---

src/arch/linux/mapping/mapping.c

The cause for the EFAULT is that the threaded vgaemu code makes
pages r/o while KVM is running. The page tables (+caches/TLB)
can then be temporarily out-of-sync. Simply retrying KVM_RUN
fixes the issue, because by then everything is synced again.

KVM: if KVM fails with EFAULT, retry. Fixes #116 (Micro Machines).

---

src/arch/linux/mapping/mapping.c
src/emu-i386/kvm.c
src/include/kvm.h

This now fixes the race by mapping directly into non-aliased memory.
This will also help the KVM + DPMI patch -- I had to put in some funny logic to allow some maps and not others.

KVM: map directly into non-aliased memory.

---

src/tools/debugger/mhpdbg.c

This patch allows a tc command to be halted if a breakpoint is
encountered. This is useful for logging the actions of a function or
interrupt call. See the following transcript:
Note: the indentation is awfully inconsistent in the file src/tools/debugger/mhpdbg.c.
~~~
system state: stopped
AX=0000  BX=037c  CX=0586  DX=0112  SI=0023  DI=0300  SP=0a80  BP=0000
DS=0112  ES=0112  FS=0000  GS=0000  FL=000a3346
CS:IP=002c:8264       SS:SP=0112:0a80
002c:8264 E8DBBE           call 4142 ($-4125)
u
002c:8267 07               pop  es
002c:8268 9C               pushf
002c:8269 36A08300         mov  al,ss:[0083]
002c:826d 98               cbw
002c:826e 40               inc  ax
002c:826f 750A             jne  827B ($+a)
002c:8271 48               dec  ax
002c:8272 7507             jne  827B ($+7) …

Dosdebug: allow tc command to respect breakpoints

---

src/include/mhpdbg.h

This ineffective define has been around at least since sourceforge svn
import in 2003. We don't need it and the value, if it ever was correct,
is now wrong.

dosdebug: Remove outdated artifact

---

etc/dosemu.conf
etc/global.conf
man/mkfatimage16.1
src/base/init/lexer.l.in
src/base/init/parser.y.in
src/base/misc/disks.c
src/include/disks.h
src/tools/periph/Makefile
src/tools/periph/mkfatimage16.c
src/tools/periph/mkhdimage.c

A couple of tweaks to peripheral programs to allow specific geometry hdimages to be created. A further change to disks.c allow the virtual hd disk created from a directory to be presented with known geometry that requires FAT16B filesystem. An IBM type 9 disk having CHS of 900/15/17 geometry was chosen. This enables easy comparison of hdimage and vfs directory boot logs, by ensuring the filesystem geometry is identical.

Test support 01

---

mkpluginhooks

I'm trying to build dosemu2 in an alpine linux based docker container (for some good fun!). Alpine is a musl based distribution with base BusyBox binaries. The `find` command doesn't have the -printf option, so I've made a patch to handle this. Will keep you posted re: other build issues on this platform. Thanks!

use POSIX compliant `find` in mkpluginhooks

---

src/plugin/alsa/mid_o_alsa.c

Tidies up log destination from stderr to dosemu's boot.log with debug
flag -S, mentioned in issue #227

Alsa: redirect library logging from stderr to logfile

---

src/arch/linux/mapping/mapping.c
src/plugin/commands/commands.c

This patch series:
- [fixes #230] to remove the 32bit specific compilation warnings. Tested on 32bit, Q_printf formats appear to be correct, but would appreciate confirmation on 64 bit
- fixes the table alignment when printing dpmi info within DOS
Compiled on both 32 and 64 bit okay

Printf types 01

---

etc/global.conf

Allow floppy boot to find images and directories with relative paths under imagedir if not found under ~/.dosemu. Helps ease the path for #236 removal of vbootfloppy

Little fix to allow boot from a floppy_a under imagedir

---

src/base/misc/fatfs.c

There seem to be at least two versions of DR-DOS 7.02 in the wild and
Wikipedia suggests there may be more. Add the string 'DR-OpenDOS' to the
whilelist of medium age DR-DOS versions so that detection may succeed.
[fixes #250]
Test run after fix applied
~~~
Test DR-DOS-7.02-971119 FAT12 vfs directory ... ok
Test DR-DOS-7.02-971119 FAT16 vfs directory ... ok
Test DR-DOS-7.02-971119 FAT16B vfs directory ... ok
Test DR-DOS-7.02-971119 MFS redirection ... ok
Test DR-DOS-7.02-971119 SysType ... ok
Test DR-DOS-7.02-971119 VBFLPY ... ok
Test DR-DOS-7.02-980123 FAT12 vfs directory ... ok
Test DR-DOS-7.02-980123 FAT16 vfs directory ... ok
Test DR-DOS-7.02-980123 FAT16B vfs directory ... ok
Test DR-DOS-7.02-980123 MFS redirection ... ok
Test DR-DOS-7.02-980123 SysType ... ok
Test DR-DOS-7.02-980123 …

fatfs: support for booting OpenDOS 7.01 & 7.02 (971119)

---

src/base/misc/fatfs.c

The previous value of 14 root sectors was only good for 1.2 and 1.44
size floppies. Set the value based upon type to help older OSes that
don't support the higher capacity media.
Before this change, the following OSes failed to boot with 360KB floppy:
FAIL: Test MS-DOS-3.10 Floppy vfs directory
FAIL: Test PC-DOS-3.00-Compaq Floppy vfs directory
FAIL: Test PC-DOS-3.00 Floppy vfs directory
FAIL: Test PC-DOS-3.10-850307 Floppy vfs directory
FAIL: Test PC-DOS-3.10-850422 Floppy vfs directory
FAIL: Test PC-DOS-3.10-Compaq Floppy vfs directory
Afterwards, all but the following successfully booted:
FAIL: Test MS-DOS-3.10 Floppy vfs directory

disks: Floppy root sector size depends upon type

---

src/bindist/autodos7.bat
src/bindist/autoemu.bat
src/bindist/autoexec.bat

This allows -cdrom to work when it points to a path with spaces.

Prevent problems when using paths containing spaces.

---

src/arch/linux/Makefile.main
src/base/misc/utilities.c

Dosemu executables installed via Debian packages were mistakenly
looking in /usr/lib/x86_64-linux-gnu/dosemu/ for the plugins. Change
the location to use the value supplied via --with-plugindir= as is
used for their installation. [ fixes #282 ]

build: Search plugindir for plugins

---

src/commands/Makefile
src/plugin/commands/Makefile

This is required by the later toolchains used on Ubuntu Yakkety & Zesty
else we get the following during build on 64 bit:
~~~
gcc -Wl,-warn-common -Wl,-Bsymbolic-functions -Wl,-z,relro
-Wl,--section-start=.text=0x100,-e,_start16 -nostdlib -o isemu.com.elf
isemu.o
/usr/bin/ld: isemu.o: relocation R_X86_64_16 against `.text' can not be
used when making a shared object; recompile with -fPIC
/usr/bin/ld: section .interp LMA [0000000000000200,000000000000021b]
overlaps section .text LMA [0000000000000100,00000000000002a4]
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:47: recipe for target 'isemu.com.elf' failed
make[3]: *** [isemu.com.elf] Error 1
~~~
Tested for basic functionality and build on Yakkety 64bit, Xenial …

build: Add -static to link DOS executables

---

src/dosext/misc/emm.c

Tested for compilation and basic dosemu startup only. No functional change intended.

emm: remove redundant macro

---

src/base/async/int.c
src/dosext/dpmi/dpmi.c
src/dosext/misc/emm.c
src/include/int.h

Chinese win32?). Use an enum to indicate the the mode instead. This
should not have any functional impact.

Rename win31 to win3x as it also applies to win30 and win311 (and

---

src/base/async/int.c

As per discussion in #347, mfs_lfn() was not being called in DOS versions 3.10 ..  3.21
@bartoldeman 
>dos_post_boot is triggered by int2f/ax=ae00, called by command.com in DOS 3.3+. See http://www.ctyme.com/intr/rb-5189.htm. For DOS < 3.3 something else would need to trigger dos_post_boot (e.g. Stas' proposal of using emufs.sys).

mfs: Fix long filename support for v3.10 .. v3.21 DOS

---

debian/rules

By changing the location that the xfonts are installed to be the
standard place, the Debian packaging helpers are used automatically
to update the font cache, and there's no need to mess with the font
path. [fixes #364]

deb: Change the xfont install location

---

Makefile
debian/rules
src/arch/linux/Makefile.main

These patches fix the problem with `*.pcf.gz` not being built, and a few other issues, when the source directory differs from the build directory.

More patches to make separate $srcdir work

---

mkpluginhooks

when building packages (e.g. for openSUSE Linux)
(random) filesystem order of input files
influences ordering of functions in the dosemu.bin output,
thus without the patch, builds (in disposable VMs) would differ.
See https://reproducible-builds.org/ for why this matters.
Note: change is not tested (only a similar one on 1.4.0.1)

sort linker input files

---

src/base/video/remap.c

Remappers for converting 15/16-bit VESA mode to 32-bit X mode when running in fullscreen.
Support for 24/32-bit VESA modes and 16/24-bit X modes has to come later.

Add remapper for 15/16-bit to 32-bit colours in fullscreen under X

---

src/dosext/misc/emm.c
src/env/commands/ems.S
src/include/emm.h

1/ Add check for ems.sys already loaded
2/ Remove unused message strings from ems.S
3/ Remove cr,lf and eom constants from ems.S, they are unnecessary
4/ Remove set of header Unit field (only valid on a block device driver)
5/ Set the proper exit status for device driver load failure

ems: Tidy ems.sys loading

---

src/dosext/mfs/mfs.c

Under both vanilla and Compaq PC-DOS the PSP was not being found due to
bad offsets within the SDA [fixes #421]. This has now been corrected,
the PSP dumped to file and sanity checked.
Here is the PSP from vanilla PC-DOS 3.00
~~~
000000 cd 20 00 a0 00 9a f0 fe 1d f0 2c 01 e8 08 39 01 >.  ........,...9.<
000010 e8 08 81 04 e8 08 e8 08 01 01 01 00 02 03 ff ff >................<
000020 ff ff ff ff ff ff ff ff ff ff ff ff bf 00 e8 01 >................<
000030 ce 0d 14 00 18 00 bd 09 00 00 00 00 00 00 00 00 >................<
000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 >................<
000050 cd 21 cb 00 00 00 00 00 00 00 00 00 00 54 48 49 >.!...........THI<
000060 53 20 20 20 20 20 20 20 00 00 00 00 00 49 53 20 >S       .....IS <
000070 20 20 20 20 20 20 20 20 00 00 00 00 00 00 …

mfs: Update SDA layouts for PC-DOS 3.00

---

src/env/commands/ems.S

Old versions of DOS (seen with PC-DOS 3.00) did not check the usual
status value in AX at load time. This can lead to the driver being
loaded and maybe because the break address was still set to %cs:0000
the CON device got corrupted. Apparently the correct method to ensure
the driver did not load is to change the driver header attribute to
signify a block device and to set the number of units provided to zero.
Tested with:
PC-DOS 3.00
MS-DOS 3.10
DR-DOS 3.40

ems: Adjust device driver error exit method

---

src/include/detect.h
src/include/macros86.h

We don't need to specify the segment prefixes by hardcoding in this way.
Replace them with assembler code to generate the same.
Test:
```
.code16
.byte 0x26
lodsl
lods   %es:(%si),%eax
```
Dump:
```
$ as -march=i386 test.S && objdump -d -M addr16,data16 a.out
a.out:     file format elf32-i386
Disassembly of section .text:
00000000 <.text>:
0:	26 66 ad             	lods   %es:(%si),%eax
3:	26 66 ad             	lods   %es:(%si),%eax
```
Validated that isemu.o is byte for byte equal now to before this change.
[fixes #429]

asm: Remove the hardcoded segment prefixes

---

src/base/misc/disks.c

disks: Hd type and number fixes
1/ Don't change an explicit hdtype
On older DOS versions that don't support FAT16B we change the hdtype
so that the geometry falls inside FAT16 filesystem limits. If the
user has explicitly specified a hdtype, for example to use
FAT12, don't change it to type 2.  Fixes #444
2/ Make hd type and clampimg independent
If a user specified an hdtype the same as the one we would set if
incompatible, the number of disks was not clamped on those versions
of DOS that require it.
Testing
MS-DOS 6.22
dosemu.conf drives/c         auto
dosemu.conf drives/c:hdtype1 set type 1
dosemu.conf drives/c:hdtype2 set type 2
dosemu.conf drives/c:hdtype9 set type 9
MS-DOS 3.30
dosemu.conf drives/c         change to type2, clamp disks 2
dosemu.conf drives/c:hdtype1 set type 1, clamp …

disks: Hd type and number fixes

---

src/dosext/mfs/lfn.c

The structure field sftt_next is a dword (far) pointer. Correctly load
a dword from this into the variable sp.
Also modifies the test for the end-of-list indicator to check only the
low 16 bits, ie the offset portion.

mfs/lfn.c: correctly advance through SFT containers

---

src/base/async/int.c
src/base/misc/dos2linux.c
src/base/misc/dump.c
src/base/mouse/mouse.c
src/base/serial/fossil.c
src/dosext/dpmi/dpmi.c
src/dosext/misc/emm.c
src/dosext/net/pktnew.c
src/emu-i386/do_vm86.c
src/env/builtins/builtins.c
src/tools/debugger/mhpdbg.c
src/tools/debugger/mhpdbgc.c

Here's the search/replace LWORD(?s) -> SREG(?s). I tried playing with updating the LWORD macro to use the static_assert to check the arg size, but was unable to figure out the syntax within the macro to allow assignment and reference of the value properly. Perhaps you could add a follow up commit for that?

regs: Don't use LWORD macro for segments

---

src/base/async/int.c

Since the title_hint variable is used outside of int2f/ae00, ensure
that the program name contains no control characters, as may be the case
when running DOS < 4.0. This interrupt handler is called by DOS to
evaluate and potentially extend the built-in commands made available by
COMMAND.COM. For that reason the program name will always be 'COMMAND',
and so if we can't resolve the program name from the MCB, it seems
reasonable to hardcode that value as at least it prevents control
character gibberish appearing in the title.

int.c: Validate the program name

---

src/tools/debugger/dosdebug.c

Repeating 'd' dump memory or 'u' unassemble commands with a fixed address
makes no sense, so translate those into a plain 'd/u' before saving in the
command history. Subsequent repeats will increment the address.
e.g.
d cs:0010
PRINTS 0070:0010 > 0070:0080
<enter>
PRINTS 0070:0090 > 0070:0100
<enter>
PRINTS 0070:0110 > 0070:0180
fixes #482

dosdebug: Don't repeat '[ud]` xxxx:xxxx' commands

---

src/tools/debugger/mhpdbgc.c

If for example a linear address is specified in 'u' unassemble, but
current address mode is 'dos', unassembly is incorrectly done from
0000:0000. Since there is a one to many relationship of linear to
seg:ofs addresses, set a normalised seg:ofs so that unassembly will be
correct and subsequent 'u' commands will be sequential.
Fixes strangeness with [#494], but doesn't alter the addr (no colon)
behaviour to match the reporter's expectation that it should represent
the offset part of a seg:off address and the segment part be defaulted
to current CS.
Note: The same problem as in #494 occurs with unix addresses found via the symbol file.

dosdebug: Set normalised seg:ofs on linear addr

---

src/emu-i386/simx86/interp.c

Note that this is only the places that *set* CeS_LOCK. As discussed in #481:
>> I also think currently CeS_LOCK does not prevent the HW irq, but maybe with the below change it will?
> 
> No idea, I don't know the dosemu CPU handling well enough.

add missing CeS_LOCK usages [fixes #481]

---

src/base/bios/bios.S
src/dosext/mfs/lfn.c
src/dosext/mfs/lfn.h
src/dosext/mfs/mfs.c

Do a single open for creating LFN files by storing the Unix filename
in a global variable, which is then used by MFS to open the file.
MFS uses sda_user_stack to detect if the passed SFN comes from lfn.c
(DS:SI=BIOSSEG:LFN_short_name).

MFS/LFN: Fix LFN file creation for r/o files.

---

src/base/misc/fatfs.c
src/include/disks.h

Musl defines `loff_t` in `fcntl.h` and `PATH_MAX` in `limits.h`.

Adding includes to improve musl libc compatibility

---

src/base/misc/dos2linux.c

Fixes following error when linking against the musl libc:
```
lib/libbase_misc.a(dos2linux.o): In function `find_drive':
dos2linux.c:(.text+0x1514): undefined reference to `canonicalize_file_name'
```
Found a bug report where this is discussed:
https://sourceware.org/bugzilla/show_bug.cgi?id=21009

Replace canonicalize_file_name with realpath in dos2linux.c

---

src/base/misc/utilities.c

utilities.c: use va_copy instead of __va_copy

---

src/tools/debugger/dosdebug.c

Previously the dosdebug client was matching only the first 4 characters
of the command for 'kill' which meant that 'killeverything' also
matched but the 'unknown command' message was displayed anyway. Tighten
the matching to look for whole string and terminating EOL character.
Fixes [#509]
Note: that the issue reports that there's a difference in the kill
behaviour, that's because the mhp dosdebug side never sent the
termination command due to 'unknown command'. Subsequently the dosdebug
client side timed out and followed up with the signal sequence of TERM
then KILL.

dosdebug: Match the whole command for kill

---

src/emu-i386/kvm.c

DPL is set to 0 in most IDT entries so that software interrupts in DPMI
GPF (which matches Linux kernel handling in native mode). However int3
and int4 (and only those) must have DPL 3 as in the Linux kernel so
they generate traps 3 and 4 instead of GPFs for INT3 and INTO instructions.

KVM: fix int 3 and int 4 handling: fixes bp in dosdebug.

---

src/arch/linux/async/signal.c
src/arch/linux/async/sigsegv.c
src/dosext/dpmi/dpmi.c
src/dosext/dpmi/dpmi.h
src/emu-i386/kvm.c
src/emu-i386/simx86/cpu-emu.c

I managed to make DPMI+KVM behave more similar to native DPMI with respect to control flow.
This way dpmi_thr() is used in both cases, only signals are not used.
I assumed that it's ok to simply keep the FPU state inside KVM all the time with no explicit save and restore; as far as I can see DOSEMU does not attempt to keep a per-client FPU state. Let me know if I understood that wrongly.

Dpmi kvm streamline

---

src/base/dev/vga/vgaemu.c
src/dosext/dpmi/dpmi.c
src/dosext/dpmi/memory.c
src/emu-i386/simx86/cpu-emu.c

These are minimal patches to fix $_cpu_emu="full" and "fullsim" (or the newer $_cpu_vm_dpmi = "emulated" -- a patch to cleanup the old syntax will come later).

Fix cpuemu for DPMI

---

src/arch/linux/async/sigsegv.c
src/emu-i386/do_vm86.c
src/emu-i386/kvm.c
src/emu-i386/simx86/cpu-emu.c
src/include/emu.h

vm86_fault does not use most scp fields, but the vm86 registers instead.
Make this explicit by only passing those fields, and removing
unneeded code around vm86_fault, and disabled code inside vm86_fault
that uses scp. Make the cr2 passed to vm86_fault relative to mem_base.

Cleanup vm86_fault: pass trapno/err/cr2 instead of scp.

---

src/emu-i386/simx86/codegen-x86.c
src/emu-i386/simx86/fp87-sim.c
src/emu-i386/simx86/interp.c

These make the output of the QEMU tests in src/tests identical for JIT, sim, KVM and native, and prepare for on-demand FP state saving.

cpuemu bug fixes

---

src/base/misc/fatfs.c

**fatfs.c: load boot sector to 1FE0h:7C00h for loading FreeDOS kernel**
When booting, the boot sector is loaded to 0:7C00h, which is
overwritten by a FreeDOS KERNEL.SYS (that is fully loaded
starting at 60h:0). Original FreeDOS boot sector loaders cope
with this by relocating to 1FE0h:7C00h, allowing the kernel to
grow to below 1FE00h+7C00h-600h = 27400h (ca. 156 KiB).
The BPB is still pointed to by ss:bp when passing control to
the kernel's entry point. This allows users of this boot load
protocol to learn what unit and what partition they're booted
from. The current FreeDOS kernel does not utilise this yet,
only noting the boot unit as passed in bl.
Similarly as for the case MOS_D, this commit loads the boot
sector to the relocated position to provide it to the loaded
kernel. This …

Mimic boot blk improvements

---

configure.ac
src/arch/linux/async/sigsegv.c
src/dosext/dpmi/dpmi.c
src/emu-i386/cpu.c
src/emu-i386/do_vm86.c
src/emu-i386/simx86/codegen-x86.c
src/emu-i386/simx86/cpu-emu.c
src/emu-i386/simx86/interp.c
src/emu-i386/simx86/syncpu.h
src/include/cpu.h

Relates to #572.
I haven't submitted any of my proposed changes to dpmi.c yet, that needs some more testing. There is also still the issue that SSE state is not saved/restored on i386.

fpstate-related cleanups and speedups

---

src/base/misc/fatfs.c

Requested in #88, but at the time there were problems booting it. Now the
7.01.08 WIP snapshot loads just fine, so something changed in the intervening
years. One observation seen in #589, is that autoexec.bat is never opened
or processed.

fatfs: Add boot support for later Enhanced DR-DOS

---

src/base/misc/fatfs.c

DR-DOS 7.01.07 needs a little more setup than the 7.01.08 WIP version.
It seems we need to load the boot sector and point DS:BP to it. With
this done both 7.01.07 and 7.01.08WIP will start successfully, but the
latter version still has the problem finding the autoexec.bat file as
mentioned in #589.

fatfs: Add boot support for Enhanced DR-DOS 7.01.07

---

src/base/bios/bios.S
src/base/dev/vga/vgaemu.c
src/base/init/init.c
src/include/bios.h
src/include/memory.h

The lower 128 characters of text font are kept in the bios at f000:fa6e
and we copy the bios in two chunks to seemingly avoid overwriting this.
However at present the bios_f000_endpart1 and bios_f000_part2 symbols are
pointing to the same address so rendering the two part copy ineffective.
>>> Existing bios.o objdump
0000f5d8 g       .text	00000000 bios_f000_endpart1
0000f5d8 g       .text	00000000 bios_f000_part2
This patch defines the bios_text_font symbol, positions it at the 0xfa6e
offset and advances the origin to avoid overwriting the text font that
may already be defined in the bios.
>>> New bios.o objdump
0000f5d8 g       .text	00000000 bios_f000_endpart1
0000fa6e g       .text	00000000 bios_text_font
0000fe6e g       .text	00000000 bios_f000_part2

bios.S: Avoid copying over text font [fixes #552]

---

src/env/commands/aspi.S
src/env/commands/ems.S
src/env/commands/emufs.S
src/env/commands/umb.S

The first change is to rename the MaxCmd label to AmountCmd, because the
current way that this label is created actually calculates the *amount*
of table entries (ie commands), not the maximum command (one less).
The second change is to use an unsigned comparison conditional branch,
ie "jbe" instead of "jle". With "jle", values that in two's complement are
below zero would incorrectly try to dispatch through the table.
The third change is to use "jb" instead of "jbe", which relates to the
different sense of the calculation as already indicated by the first change.
A command index needs to be *below* the AmountCmd value, not below-or-equal.

commands: change MaxCmd to AmountCmd, use jb conditional

---

INSTALL

It wasn't obvious to me that dosemu expects freedos to be in the current directory at this step.

clarify freedos installation

---

src/base/misc/disks.c
src/include/disks.h

As requested in https://github.com/stsp/dosemu2/issues/461#issuecomment-398392842 based on the patch I provided in https://github.com/stsp/dosemu2/issues/461#issuecomment-331267480 (but defining the I13_MAX_ACCESS constant in the header (needs to be modified to hold DERR_BOUNDARY already), and for all of CHS read and write and LBA read and write).
I also took on a number of minor changes to unify and improve some of the logging.
Not addressed by this pull request (yet):
* Floppy units may (should) fail accesses with buffers crossing a 64 KiB boundary, to imitate the floppy DMA restriction.
* CHS accesses may fail if a track boundary is crossed; but some ROM-BIOSes are known to support "multi-track" access.
* LBA accesses should check the length of the packet provided by the caller.
* LBA …

Disks boundary

---

Makefile

Now that src/include/plugin_config.h is a static stub file, don't remove
it on make clean.
Fixes #629

Makefile: plugin_config.h is under git control

---

src/base/misc/disks.c

As requested in https://github.com/stsp/dosemu2/pull/628#issuecomment-401082790
(I checked with my 686 machine from ca 2000; it returned error code 01h for when the byte field's value is below 10h.)

disks: check disk address packet size to meet minimum

---

configure.ac

in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Also use UTC to be independent of timezone.
This date call is designed to work with all variants of 'date'
Without this patch, the dosemu package in openSUSE would differ for every build.

Allow to override build date

---

configure.ac

This is a mess up of mine, although it still did work by chance.

build: Fix a syntax error in configure.ac

---

src/base/async/int.c
src/dosext/mfs/mfs.c
src/include/redirect.h

Use the public interface to setup the FATFS drives, this reduces the
reliance on the LOL and global CDS array location.
Thanks to @stsp for a substantial simplification.

MFS: Use the public interface to setup the FATFS drives

---

src/tools/debugger/mhpdbgc.c

I did a silly thing here, I tested for NULL at the top of the loop, then
moved on! [fixes #653]

dosdebug: Test for NULL after moving on

---

src/dosext/mfs/mfs.c

Clean up the redirector offset definition by removing defaults and localising them in `init_dos_offsets()`.
a) checked the current values to establish common values
b) reordered values where necessary to improve readablity
Tested across 47 DOS versions to confirm no regressions.

Mfs fixes02b

---

src/base/misc/fatfs.c

1/ Add further comments to explain the format better.
2/ Add single padding byte to avoid message truncation.
3/ Add comment regarding value for message table location value.
[fixes #681]

fatfs: Clarify the MS-DOS 7.x boot messages

---

src/tools/periph/mkfatimage16.c

We should only mark the partition active if we have a boot block.

mkfatimage16: Don't mark data partition active

---

src/base/video/remap.c

Revisited the sorting suggested in PR #418 by @bolle732, recreated against current git and one change per commit for easier review. This was done on a textual basis only, tested for compilation only
**I notice that `gen_16to16_1()` is referenced twice in the struct definition, please confirm?**

 Rearrange / cleanup the order of the remapper definitions and functions #2

---

src/dosext/mfs/mfs.c
src/env/builtins/lredir.c

If Dosemu has a drive configured for redirection, but the CDS flags are
not set for DOS to recognise it, have lredir display the DISABLED
attribute.
Note: This patch removes the CDROM unit number display code from lredir,
as it was ineffective because the corresponding bits were never set in
mfs:GetRedirection().
[Fixes #695]

MFS: Display disabled drive state in lredir

---

src/tools/debugger/dosdebug.c
src/tools/debugger/mhpdbgc.c

Add command to display the interrupt table and follow the chain for
each if the handlers referenced support the IBM Interrupt Sharing
Protocol. See the following link:
https://web.archive.org/web/20100403220515/http://www.simtel.net/product/view/id/46893
for the document INTSHARE.DOC
Example 1 (Ralf Brown's FASTMOUS and NOLPT loaded):
dosdebug> displayivec 2d
dosdebug>
Interrupt vector table:
2d  101B:0039
=> 9FF8:0017
=> 003E:40D2
Example 2 (if there's a debugger symbol in place):
dosdebug> displayivec
dosdebug>
Interrupt vector table:
00  003E:9257
01  0070:06F4
<snip>
20  003E:40CC
21  F000:F500(int_rvc_start_21)
22  0ED1:017E
<snip>

dosdebug: Display the interrupt table

---

src/base/bios/bios.S
src/tools/debugger/dosdebug.c
src/tools/debugger/mhpdbgc.c

I added a couple of symbols to bios.S for the fixed disk parameter table for display with `ivec` I was trying to correct the duplicate comment for the second entry but I'm not sure the second one is in the right place. According to [rbil](http://www.delorie.com/djgpp/doc/rbinter/id/54/61.html) the second entry should immediately follow the first.
So
First entry is at `f000:e401`
Second should be at `f000:e411` but is at `F800:6420(HD_parameter_table1)`
I also checked seabios source and they have an array
https://git.seabios.org/cgit/seabios.git/tree/src/std/bda.h#n153

Dosdebug 31

---

src/plugin/debugger/mhpdbgc.c

As per your suggestion in #750 here's a tweak to Dosdebug's ivec that displays the handler's owning program. I implemented it half as you suggested (looking up the PSP at the start of the handler's segment) and half by walking the MCB chain, which turned out to be not so difficult and had the added benefit of being able to display DOS and FREE MCB's too.

Dosdebug 33

---

src/plugin/periph/mkfatimage16.c

Year fields are 7 bits not 5 wide
Previously dates would roll over after 2012 i.e. 2019 became 1987,
whereas the proper date year range on FAT should be 1980 -> 2107
See https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system#Directory_entry
at offset 0x10

mkfatimage16: Dates year field width wrong

---

src/dosext/dpmi/dpmi.c

According to git blame this is very old codei (1996) I can only surmise that
changes to defines mean it is now compiled in as it's only just started
warning for me. Test compiled on 32 and 64 bit without warnings.

dpmi: Fix format warnings on printf

---

src/dosext/mfs/mfs.c
src/include/dos2linux.h
src/plugin/debugger/dosdebug.c
src/plugin/debugger/mhpdbgc.c

1/ Add a couple of commands for dosdebug useful when writing block device drivers.
2/ Correct long standing DPB typo.
Mentioned in #815

Dosdebug 36

---

src/include/dos2linux.h
src/plugin/debugger/mhpdbgc.c

dosdebug: Tidy up display of MCBs
1/ Use single loop and logic for MCB display
2/ Add display of DOS data subsegments
~~~
dosdebug> mcbs
dosdebug>
ADDR(LOW) PARAS  OWNER
0290:0000 0x000d [DOS]
=> ADDR      PARAS TYPE USAGE
0291:0000 0x000c [F] Files
029e:0000 0x9d60 [FREE] (END)
ADDR(UMA) PARAS  OWNER
9fff:0000 ------ [LINK]
c300:0000 0x0215 [DOS]
=> ADDR      PARAS TYPE USAGE
c301:0000 0x0009 [D] Driver (EMS)
c30b:0000 0x0008 [D] Driver (EMUFS)
c314:0000 0x0020 [B] Buffers
c335:0000 0x00cf [F] Files
c405:0000 0x008f [L] CDS Array
c495:0000 0x0080 [S] Stacks
c516:0000 0x0006 [FREE]
c51d:0000 0x12c1 [COMMAND]
d7df:0000 0x081f [FREE]
dfff:0000 ------ [LINK]
f000:0000 0x0513 [FREE]
f514:0000 0x0619 [COMMAND]
fb2e:0000 0x0090 [COMMAND]
fbbf:0000 0x0040 [COMMAND] (END)
~~~

Dosdebug 38

---

src/dosext/builtins/doserror.h
src/dosext/builtins/lredir.c

1/ Previously it was possible to delete the current drive from underneath
DOS. Add a check to prevent the user doing this.
~~~
C:\>lredir g: /tmp
G: = \\LINUX\FS/TMP attrib = READ/WRITE
C:\>g:
G:\>lredir -d g:
Redirection for drive G: was deleted.
G:\>dir
File not found. - '.'
G:\>
~~~
~~~
C:\>lredir g: /tmp
G: = \\LINUX\FS/TMP attrib = READ/WRITE
C:\>g:
G:\>lredir -d g:
Error G: is the default drive, aborting
G:\>
~~~
2/ In addition the error code for lredir delete is now returned

builtins: Add check for default drive to lredir [fixes #844]

---

src/plugin/debugger/dosdebug.c
src/plugin/debugger/mhpdbgc.c

1/ During the boot process Dosemu's LOL pointer may not be set,
so allow the user to supply an address to start printing the DPB
entries.
2/ Limit the number of DPBs displayed to 26
Use:
If using FDPP you can get the address from GDB as follows:
~~~
(gdb) p/x  LoL->_CDSp[0].cdsDpb
$32 = {ptr = {off = 0x19e8, seg = 0xd9}}
~~~
Here the chain is displayed starting at F: address, not the A:
address above.
~~~
dosdebug> dpbs 00D9:1B19
dosdebug>
DPBs (compiled for DOS v4+ format)
00D9:1B19 (F:)
driver unit: 5
bytes_per_sect = 0x200
last_sec_in_clust = 0x3f
sec_shift = 0x6
reserv_secs = 0x1
num_fats = 0x2
root_ents = 0x200
data_start = 0x217
max_clu = 0xfa00
sects_per_fat = 0xfb
first_dir_off = 0x1f7
device driver = 0070:0618
media_id = 0xf8
accessed = 0x0
next_DPB = 02C0:0000
first_free_clu = …

dosdebug: Allow user to specify DPB start address

---

src/base/misc/dos2linux.c
src/dosext/builtins/builtins.c
src/dosext/builtins/builtins.h
src/dosext/builtins/lredir.c
src/dosext/builtins/system.c
src/include/dos2linux.h

Lredir needs to know what the next unused drive is for its '-n' map next
free drive etc. The best way to find out whether a drive is in use is to
ask DOS because examining the drives array is not sufficient when disk
images are used with multiple partitions(#768).
The log below shows the difference, prior to this patch the 'I:' would
be chosen, whereas afterwards it is 'M:'
~~~
FDPP kernel 0.1beta7 [GIT: beta-7-6-g05bf29d] (compiled Jul  8 2019)
Kernel compatibility 7.10 - GNUC - 80386 CPU required - FAT32 support
Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software …

lredir: Ask DOS if drive is free [fixes #768]

---

src/base/core/int.c
src/dosext/builtins/builtins.c
src/dosext/builtins/msetenv.c
src/dosext/misc/xms.c
src/include/cpu.h
src/plugin/fdpp/fdpp.c

The macro SEG2LINEAR was incorrectly named as in fact it returns a unix
pointer rather than linear address value, so rename it to SEG2UNIX and
change all its callers. Mentioned in #763

macros: Rename SEG2LINEAR to reflect its use

---

src/include/dos2linux.h
src/plugin/debugger/dosdebug.c
src/plugin/debugger/mhpdbgc.c

Procedure:
1/ Find the addresses of the driver's strategy and interrupt routines using the 'devs' command.
2/ Review the strategy routine to see where the address of the request header will be stored each time it's called.
3/ Set breakpoints at entry and exit of the interrupt routine
4/ Run until first breakpoint is hit 'entry'
5/ Display the request header pointer
6/ Display header on entry with the new command like 'ddrh ADDR' using
the address held in the pointer above
~~~
xmsdsk_interrupt:
02c5:00b2 9C               pushf
dosdebug> ddrh 00d8:037c
dosdebug>
Request
length 30
unit   0
command 'Media Check'
media id 0xf8
status 1
status 0x0000
~~~
7/ Run until stop on 'exit' break point set
~~~
xmsdsk_interrupt_return:
02c5:00d9 CB               retf
dosdebug> ddrh 00d8:037c
dosdebug> …

dosdebug: Add command to display device driver request

---

test/test_dos.py

Simple call of int21/71a6 for two files, one 1MiB and another at 6GiB. This is using sparse files to avoid having an especially large amount of free space. It's also important that the test file resides in a directory that won't be used to create a fatfs disk, else the sparse file will be copied to a fully allocated file during fatfs creation.
Incidentally I also ran these tests against FreeDOS 1.20 to check the bios.s implementation and both passed too.

Travis: Add test for int21/71a6 LFN file info

---

src/plugin/debugger/mhpdbgc.c

Noticed in https://github.com/stsp/fdpp/issues/112 tracing `t` can give
incorrect DOS execution, whereas tracing in `ti` behaves properly. It
has been isolated to the trace handler added in 158fe96, for now avoid
using that code on likely problem interrupts.

dosdebug: Avoid trace handler on ints 21/2f/28/33

---

src/base/core/int.c

int.c:1214:31: runtime error: left shift of 48871 by 16 places
cannot be represented in type 'int'

int.c: Shift error on 32 bit [fixes #960]

---

src/plugin/debugger/dosdebug.c

Since the 'tc' command runs until keypress, we don't want to repeat
that command upon empty line. In the case of 'tc' command store just 't'
for its subsequent repeat.

dosdebug: Don't repeat 'tc' command

---

src/base/emu-i386/kvm.c
src/base/emu-i386/kvmmon.S
src/dosext/dpmi/dpmi.c
src/include/kvm.h
src/plugin/debugger/mhpdbgc.c

This is my patch adapted to Stas' notation.
I'm still not sure about 0x70-0x77, 0x1c, 0x23, 0x24 so kept excluding them just to be cautious.

kvm: use native IDT for speed-up [fixes #982]

---

src/base/emu-i386/kvm.c
src/base/emu-i386/kvmmon.S

Here are some of the requested IDT changes:
1. DPMI in KVM will now use IDTs > 0x10 directly for software interrupts.
2. Extended direct IDT use to ints 0x11-0x1f (since those exceptions can never happen)
3. Eliminate the special 0xff hw int injection, by using ioctls to get and set registers. I'm not using the kvm_sync_regs structures since that requires new-ish kernels (4.18+) and the speed is not affected much since the ioctls only apply for signals, and sets only if the registers have changed (which either means a hardware int or some kind of callback / coopthread magic).
Ideally I'd inject hardware ints into KVM, and maybe even use its builtin PIC but that's for another day (then hardware ints go via the IDT and must then be reflected to the vm86 IVT).

KVM IDT changes (part 2)

---

src/base/dev/pic/pic.c
src/dosext/net/ipx.c
src/dosext/net/pktnew.c

…pending
Ever since commit 8bf6af908 from 2005 the while loop to run do_irq() no longer
makes sense, since the ints are now run via the main loop. Mostly that doesn't
matter since outside special mask mode (through the priority mechanism)
only one IRQ can be scheduled at the same time anyway, so the while loop would
only run once.
However if special mask mode is enabled, lower priority IRQs can still be
scheduled but are blocked as long as interrupts are disabled. So to make them
run asap once interrupts are enabled, set VIP.
do_irq() may also use a callback which will do a fake int to a HLT (VIF not
reset) so will return asap anyway even without VIP.

pic: run_irqs: "while"->"if", set VIP if other IRQs pending

---

src/base/emu-i386/kvm.c
src/dosext/dpmi/dpmi.c

Now by default for DPMI ints > 0x10 go via the IDT to a HLT at
DPMI_SEL_OFF(DPMI_interrupt) + i in dpmi_sel.
We still need DPL=0 for dosdebug (where it is similar to the use
of the int_revectored bitmap for real mode ints) and exceptions.

KVM: use DPL=3 for IDT even in non-debug default case

---

test/test_dos.py

Start two FindFirst (one wild, one plain) with different DTAs,
then check we get a proper result with FindNext using the first
DTA. See PR #1010
Thanks to @bartoldeman for the skeleton test in NASM

Travis: Add DOS v2 FindFirst/FindNext mixed DTA tests

---

src/base/emu-i386/kvm.c

KVM is sometimes interrupted with X86_EFLAGS_RF set, and that bit was unconditionally
reset, which caused unexpected GPFs with long running DPMI applications. It is now
preserved if cs:eip and X86_EFLAGS_VM remain the same so we are still at the same
instruction.
Without this fix compilation of FreeCOM with Open Watcom crashes at some random
point.

KVM: preserve RF if necessary (fix regression in 5fbac93e)

---

src/dosext/dpmi/dpmi.c

At least on i386 kernel 4.19 is picky about the size of the area that fpregs
points to. We know for sure that what fpregs points to on signal entry is
fine so don't change and copy FPU state to it instead of setting the pointer.
Without this fix I got hard SIGSEGVs (no backtrace) on i386 native DPMI as
soon as a DPMI prog is started and dmesg messages such as
"dosemu.bin[32058] bad frame in rt_sigreturn frame:30e78129 ip:17a1 sp:7f0
orax:ffffffff in memfd:dosemu_32058 (deleted)[0+b8000]"

DPMI native: don't change fpregs pointer in sigcontext

---

src/include/memory.h

This avoids undefined behaviour sanitizer (UBsan) generated messages such as
runtime error: pointer index expression with base 0x00000000 overflowed to 0x80000000
for 32-bit builds.

MEM_BASE32: change order of casts.

---

configure.ac

This was useful for me as I have a mostly 32-bit userspace but often
run with a 64-bit kernel, and the default target for gcc is then -m32.
The compilation should then choose between -no-pie and -pie depending on
GCC's (or Clang's) default target instead of the kernel's arch `uname -m`
that is running during compilation.

Use $CC -dumpmachine to determine default target machine.

---

src/base/emu-i386/simx86/interp.c

MAKESEG modifies basemode so we can't pass it by value.
With this change fullsim works properly again, but the JIT still has issues
for DPMI (which can now be identified using src/tests/test-i386).

CPUEMU: Fix regression from b63f6f6 for 32-bit DPMI

---

src/arch/linux/async/sigsegv.c
src/arch/linux/mapping/mapping.c
src/base/dev/vga/vgaemu.c
src/base/emu-i386/kvm.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/sigsegv.c
src/base/init/init.c
src/include/vgaemu.h

I had accidentally compiled dosemu2 for i386 without -no-pie (which means
pie on Debian), and got the mmap_min_addr error, which was confusing.
It can actually run if instead of this memory layout:
0   0x110000          ...           ... 1G
low dpmi_lin_rsv_base ... dpmi_base ...
you use this (as a fallback only!)
0   ...                             ... 1G
low ... dpmi_lin_rsv_base dpmi_base ...
the order hasn't changed, only the position of the hole. This helps pie
or the unlikely case when kernels/libcs allocate other things just above
0x110000 (as was done in the past with execshield).
(I'll explain the accident in another PR)

vm86: allow pie-compiled 32-bit dosemu2 to run

---

src/base/emu-i386/kvm.c

Commit e340b209 accidentally also added RF to the RETURN_MASK but it should
not be there as pushfd needs to clear RF in the stack image (see e.g.
https://www.felixcloutier.com/x86/pushf:pushfd:pushfq
)
This fixes the test-i386.exe tests that use KVM.

KVM: remove RF from RETURN_MASK.

---

src/base/emu-i386/simx86/interp.c

int3 (BP) and into (OF) are special: matching the Linux kernel they must generate
traps 3 and 4, and not GPF, and therefore not set an error code.
This fixes the test-i386.exe test completely for the simulator, and partly
for the JIT.

CPUEMU fix error code for exceptions 3 and 4

---

test/common_framework.py
test/test_dos.py
travis_build.sh

Most still fail, so this PR can be used to track various CPUEMU fixes to do.
(I never thought I'd be programming in Python for DOSEMU but here you go :)

Add CPU tests to the Travis framework.

---

.travis.yml

This enables the KVM CPU tests to run as intended, rather than fallback
to emulation. [#1026]

Travis: Install and configure KVM

---

src/base/emu-i386/simx86/memory.c
src/base/emu-i386/simx86/sigsegv.c

Cpatch can't be used for DPMI page faults (e.g. with DJGPP null pointer
protection as tested in test-i386.exe: that test is fixed with this change),
so we must check if the address is either VGA memory or protected by cpuemu.
Using Cpatch is a strategic place in e_vgaemu_fault allows using Cpatch
on VGA memory then but unfortunately that still produces glitches in Jazz
Jackrabbit (which are also there without the revert).
The one thing left from acee39e is to allow Cpatch for code hits.

simx86: mostly revert acee39e (extensive use of Cpatch)

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/sigsegv.c
src/base/emu-i386/simx86/syncpu.h

The use of LODS/STOS is temporary, they will be replaced with L_DI_R1
and S_DI later. This way there is no more MOVS in generated code without
REP, so the cpatch and sigsegv code can also be simplified. See also #1033
(not fixed completely for Jazz yet) and #156.

simx86: replace use of O_MOVS_MovD without REP with O_MOVS_LodD/StoD

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/emu86.h
test/test_dos.py

test-i386 was randomly failing floating point tests where the FP environment
was not properly set restored. The cause was that for code sequences that use
FP that FP flag was not always set, which was the fault of the node linker.
The node linker needs to not only flag FP for the node that links to the new
sequence but also any other nodes that link to it, so I added a recursive
function to flag all back references. It can stop at any back reference that
was already flagged since those were treated earlier with all their back
references.
test-i386 now passes completely for "full" JIT cpuemu so I added it to the
Travis tests.

simx86: fix floating point flagging of nodes in JIT

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/sigsegv.c

This way there is no more scas in generated code without rep, so
the sigsegv code can also be simplified.
(Next cherry pick from #156)

simx86: replace use of O_MOVS_ScaD without REP with L_DI_R1/O_CMP_FR.

---

src/dosext/dpmi/msdos/callbacks.c
src/dosext/dpmi/msdos/callbacks.h
src/dosext/dpmi/msdos/msdos.c

Some programs read directly to VGA memory (e.g. Jazz Jackrabbit),
so we must use memcpy_dos2dos and not memcpy_2dos/memcpy_2unix.
This fixes its display of sprites.
Partially reverts commit 13c4180a.

dpmi: msdos: use dosaddr_t for io_buffer and memcpy_dos2dos.

---

src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/memory.c
src/base/emu-i386/simx86/trees.c
src/base/misc/dos2linux.c
src/dosext/dpmi/msdos/msdos.c

This follows up from #1039 to eliminate the `ERROR: touched jit-protected page` errors from Jazz Jackrabbit.

Speed up e_invalidate and use it in memmove/memcpy functions

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/sigsegv.c

This way there is no more cmps in generated code without rep, so
the sigsegv code can also be simplified.
(Next one from #156)

simx86: replace use of O_MOVS_CmpD without REP with LodS/custom.

---

src/base/kbd_unicode/keynum.c
src/include/keyboard/keynum.h
src/plugin/sdl/keyb_SDL.c
src/plugin/sdl/sdl2-keymap.h

This avoids an assert crash as in #1045 for volume up/down, mute, bookmark,
f13-f24, though it's not complete. Using
https://github.com/qemu/keycodemapdb/blob/master/data/keymaps.csv
the list could be completed.

SDL/keyboard: add some keynums for multimedia/misc keys

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen.h
src/base/emu-i386/simx86/interp.c

The PUSH() inline function was passed &ocs where ocs is unsigned short,
but then cast it to *(int *), which could push garbage onto the 32bit
stack. Avoid this tricky behaviour by passing by value instead.
This caused buggy behaviour where cs could be >0xffff with the Causeway DOS
extender.

simx86: fix cs value pushed for 32-bit far call/jmp

---

src/base/dev/vga/vgaemu.c
src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/sigsegv.c
src/include/vgaemu.h

This needed the definition of vga_read_dword that was missing in
vgaemu.c.

simx86: Make e_VgaMovs less cumbersome to use and clean it up.

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/sigsegv.c

The expensive part of e_vgaemu_fault() is now completely eliminated.

simx86: move "rep scas"/"rep cmps" vgaemu handling to cpatch.c.

---

src/dosext/dpmi/dpmi.c

we need them to use memcpy_2dos which invalidates JIT-protected DPMI memory.
(could be more complete of course, this is just the minimal fix to solve some real life cases using Open Watcom with the Causeway extender)

dpmi: dosaddr_t for GetDescriptor/GetFreeMemoryInformation

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/codegen.h
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/modrm-gen.c

The dpmi/msdos LDT emulation code emulates POP on memory which got the wrong
value of ESP for page faults in full JIT and fullsim mode, so it needs to be
adjusted back to the original value before writing to memory.
This allows Windows 3.1 to run in full JIT and fullsim mode, although the
double CPU emulation is quite expensive!

simx86: fixup ESP in case POP [memory] page faults

---

src/bindist/autoemu.bat

Not sure why this was not kept in sync, but now it works properly again. I tested it with MS DOS 6.22.

fix autoemu.bat similar to autoexec.bat

---

src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/sigsegv.c
src/dosext/dpmi/msdos/msdos_ldt.c
src/dosext/dpmi/msdos/msdos_ldt.h

Rather than double emulation, use Cpatch to deal with LDT writes in the same
way as VGA writes.

simx86: jit: handle LDT writes via Cpatch

---

src/base/emu-i386/simx86/codegen-sim.c

Immediate bitops use a load/store scheme but the simulator was working
directly on the memory.

simx86: fix immediate bitops on memory in sim mode

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/protmode.c
src/base/emu-i386/simx86/protmode.h

in combination with #1064 this allows running Windows 3.x without page faults

simx86: do LDT writes without faulting in sim mode

---

src/base/emu-i386/simx86/memory.c

Fixes
src/base/emu-i386/simx86/memory.c:103:46: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'

simx86: fix UBSAN for shifting signed int quitting Win3x

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/interp.c

This can be done by adding the bit offset to the effective address, and
this way Cpatch, VGAEMU etc can work correctly on these instructions.

simx86: handle bitops to memory via load/store

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/protmode.h
src/base/emu-i386/simx86/sigsegv.c
src/base/misc/dos2linux.c
src/include/cpu-emu.h
src/include/dos2linux.h

I put the write_* functions in dos2linux.c since they are useful in other
places too, with a little modification (future work).
e_VgaWrite() has been eliminated.

simx86: introduce write_byte/word/dword, use in sim mode.

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-sim.h

There are still some direct DOS memory r/w's in interp.c and fp87-sim.c, once those are done AR1.d can be a `dosaddr_t` instead of a pointer.

Finish conversion to read/write funcs in codegen-sim.c

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-sim.h
src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/fp87-sim.c

Now that all direct memory accesses are gone we don't need to add
and subtract mem_base to segment bases any more.

simx86: use "dosaddr_t" addresses throughout in sim mode

---

src/base/emu-i386/simx86/codegen.h
src/base/emu-i386/simx86/host.h
src/base/emu-i386/simx86/interp.c

Now all memory accesses in the simulator use the read/write functions, so after this PR I can eliminate the page fault handler for the simulator.

simx86: use read/write functions in interp.c

---

src/dosext/dpmi/dpmi.c

This fixes dpmi_is_valid_range so it can be used in a future PR to check for page faults, one bug fix and one extension to mapped (virtual) hardware RAM such as the VGAEMU LFB.

Fix dpmi_is_valid_range

---

src/dosext/mfs/mfs.c

Clipper expects the DOS error to be SHARING_VIOLATION not
FILE_LOCK_VIOLATION as per the following code snippet.
```
// for network open error, set NETERR() and subsystem default
if ( e:genCode == EG_OPEN
.and. (e:osCode == 32 .or. e:osCode == 5)
.and. e:canDefault )
NetErr(.t.)
return (.f.)
end
```
Tested with TESTLOCK.ZIP and test #3 still passes.
~~~
Test #3:
Open of "d:\TESTLOCK.TMP" for REPLACE was successful, handle=5
Wrote 128 bytes at offset 0 to handle 5.
File length is now 128
Open of "d:\TESTLOCK.TMP" for REPLACE failed, _doserrno=32=SHARING_VIOLATION
This is a retriable/sharing error, which is normal here (but TLIB wouldn't
retry it)
Open of "d:\TESTLOCK.TMP" for APPEND failed, _doserrno=32=SHARING_VIOLATION
This is a retriable/sharing error, which is normal here (TLIB would …

mfs: Change temporary share error as Clipper expects

---

src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/protmode.c
src/base/emu-i386/simx86/protmode.h
src/base/emu-i386/simx86/sigsegv.c
src/base/misc/dos2linux.c
src/dosext/dpmi/dpmi.c
src/dosext/dpmi/dpmi.h
src/include/cpu-emu.h

Instead of using the host MMU, check memory accesses for valid memory, and
simulate a page fault when necessary.
Without optimizations this slows the simulator down, by a factor 2.5 or so
for test-i386.exe.

simx86: simulate page faults in DPMI.

---

src/base/dev/vga/vgaemu.c
src/base/emu-i386/simx86/trees.c
src/base/misc/dos2linux.c
src/include/dos2linux.h

This adds a cache with 4096 rounded down unprotected page addresses, indexed
by bits 12..23 of the address, see http://www.emulators.com/docs/nx08_stlb.htm
for how this works.
This speeds up the checks for unprotected pages, otherwise the faultless sim
will be too slow.

simx86: Add cache of unprotected pages for read/write functions.

---

src/dosext/dpmi/dpmi.c

This fixes a simulated page fault when running Win31 on top of
comcom32.exe, so there are at least 2 DPMI clients active.
Fixes #1100.

dpmi: check all clients' memory, not just current's

---

src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/host.h
src/base/emu-i386/simx86/protmode.c
src/base/emu-i386/simx86/protmode.h
src/base/misc/dos2linux.c
src/include/cpu-emu.h
src/include/dos2linux.h

Otherwise call dosemu_error and terminate.
This also moves some simx86-independent checks to dos2linux.c.

simx86: only longjmp for invalid access if Interp86 is active.

---

src/base/dev/vga/vgaemu.c

This fixes a regression in vga_memset{wl} where len was used after modification.

vgaemu: Fix regression from #1109 (a73d446)

---

src/base/core/dyndeb.c
src/include/dosemu_debug.h

debug_level() was quite time-consuming (up to 17% of JIT execution time).
By turning it into a macro the letter (array index) is known at compile time
which produces much more efficient code, even at -O0.
debug_levels[] was moved to a separate array so the rest of the fields of the
debug[] array can remain static.

debug_level: turn into a macro for efficiency

---

src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/syncpu.h

Just keep those flags (ID,AC,NT, which in v86 mode just serve CPU detection
algorithms) in TheCPU.eflags, as there is no danger having them
there unlike in real flags. IOPL is a bit special but pushf will need to
set that to 3 on the stack image anyway so a program can't flip it visibly.
This makes pushf, popf, int and iret a little simpler so easier to compile.

simx86: eliminate TheCPU.veflags for vm86

---

test/common_framework.py
test/test_dos.py
travis_test.sh

Just a test for now that uses standard config.sys files for
- FDPP (emufs.com disabled)
- FreeDOS (made drive agnostic)
- Generic (himem, and shell options removed)
Also enables MS-DOS 6.22 testing

Travis ci 17

---

src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/interp.c

Changing IOPL to 3 the INT instruction was now always trapped into a GPF instead
of quickly going back into the emulator when possible.
I've now fixed this and made the logic more like the Intel docs, in that
it uses the bitmap only for CR4.VME, and so I set TheCPU.cr[4]=CR4_VME at
init time, and it handles IF and VIF correctly depending on IOPL.

simx86: fix INT xx (performance regression from a7e3612d4)

---

etc/dosemu.conf

Corrected name of PDF printer; brief explanation; two spellings corrected.

Correct name for PDF printer

---

src/base/dev/vga/vgaemu_modelist.h

Would you be willing to consider this PR? It mostly extends the changes that you've already made, and it lets dosemu2 display the same text modes that I've built into my DOSBox-X system for running WordPerfect for DOS. If we had a way to add custom text modes without patching, I would use that instead, but I don't see that coming soon.
Simple description:
This PR changes the font used by some Trident text modes from 8x14 or 19x14 to 9x16, which seem more useful on modern systems. Some of the modes already in the file are already larger than the original, so this is not a major change.

Use 9x16 font for some Trident text modes

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/codegen-x86.h
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/fp87-x86.c
src/base/emu-i386/simx86/trees.c
src/base/emu-i386/simx86/trees.h

Replace global variables CodePtr, GenCodeBuf, and BaseGenBuf with locals.
Replace some use of InstrMeta global array with locals.
Also eliminate the no longer used VgaAbsBankBase.

simx86: cleanup: eliminate some global variables

---

src/base/emu-i386/simx86/interp.c

When generating code, check every PC address to avoid code
nodes overlap.
This should likely slow things down a lot, and there is a lot to
optimize in that patch series, but lets start from the slow but
correct code, rather than from fast and broken.
This was the most difficult bug in the entire dosemu2 project's
life span. Given that it didn't require any reverse-engineering
efforts on DOS side, and yet was times more difficult than the
ones that do require reverse-engineering, its a reason to celebrate. :)

simx86: check every address at gen to avoid overlaps [fixes #86]

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/codegen.h
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/trees.c

The code generator can set those directly, no reason to use the global TheCPU.mode
and then shift right by 16.

simx86: don't use TheCPU.mode for sequence flags.

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/trees.c

This is a regression from 5411f5b21: old flags were now erroneously kept.

simx86: initialize flags for new IMeta's

---

.travis.yml

As per the new knowledge gained from the discussion in #1181 change how
we gain access to the kvm device node by using Bart's previous
suggestion from #1030.

Travis: Change how we can use kvm

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/trees.c
src/include/cpu-emu.h

if we have two "mov ss" or "pop ss" instructions in a row, the second one
should not inhibit interrupts again. For the interpreter this was most
easily done using a new CeS_MOVSS flag, which can then be checked in
combination with CeS_INHI, which is then set for the first instruction,
and checked and reset for the second.
The logic now handles CeS_TRAP/CeS_SIGPEND itself so HandleEmuSignals no
longer needs to fiddle with CeS_INHI.

simx86: fix two contiguous inhibiting instructions [#1214]

---

etc/dosemu.conf
etc/global.conf
man/dosemu.bin.1.in
src/base/core/dyndeb.c
src/base/core/ports.c
src/base/init/config.c
src/base/init/lexer.l
src/base/init/parser.y
src/base/misc/Makefile
src/base/misc/dos2linux.c
src/base/misc/mmio_tracing.c
src/include/dosemu_debug.h
src/include/emu.h
src/include/mmio_tracing.h

This PR is basically an implementation of the feature request #1161.
It adds the option to set `$_trace_mmio` in the configuration file. With enabled debug printing (`-D+F`), memory mapped i/o transactions are logged. It is only working for an fully emulated CPU (set by `$_cpu_vm="emulated"`, `$_cpu_vm_dpmi="emulated"` and `$_cpu_emu="fullsim"`).

memory mapped i/o traceing

---

src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/memory.c
src/base/emu-i386/simx86/trees.c

Instead of calling e_munprotect explicitly, let e_unmarkpage check if
any code is left and if not, unprotect the relevant pages.
This way multiple partial e_unmarkpage calls that only affect parts of
pages can now still cause the page to be unprotected, thereby avoiding
unnecessary faults.

simx86: let e_unmarkpage call munprotect on demand

---

src/base/emu-i386/simx86/cpatch.c
src/base/emu-i386/simx86/trees.c

If code is invalidated for aliased memory it's not necessary to invalidate
the whole page, as just the node needs to be recompiled, keeping the page
protected.
Booting FreeDOS this helps with dynamically modifying intxx instructions and
reduces the number of page faults and recompilations by about 3-4% (info
from compiling with PROFILE and running -D+e).

simx86: invalidate node only for aliased (vm86) memory

---

src/base/emu-i386/simx86/interp.c

Since cfdff90 indirect jmps and calls use JumpGen, but those can use segment
overrides, e.g. "jmp far cs:[bp]". The cs: prefix was not taken into account
by PC but P0 points to it. This meant the saved value (in dnpc) was off by one
which could cause issues with BreakNode putting the return PC from the
tail code at "jmp far [bp]", losing the prefix and jumping to the wrong place.

simx86: JumpGen must use P0 for NewIMeta, not P2 (=PC)

---

src/base/emu-i386/simx86/econfig.h
src/base/emu-i386/simx86/memory.c
src/base/emu-i386/simx86/trees.c

e_querymark must return false for the range touched by InvalidateNodeRange,
otherwise the relevant bitmaps are out of sync and pages that must be
unprotected can remain protected.
(The tests will fail with this commit).

simx86: make sure page mark bitmaps are kept in sync

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/trees.c
src/base/emu-i386/simx86/trees.h

By adding a hash-table like cache to FindTree, indexed by the low 12 bits
of the PC we can obtain a 99.99% hit rate and speed up searches so FindTree
is sped up by a factor 3, and goes from 12% to 4% of total execution time.
This obsoletes most uses of LastXNode.
See also the discussion at #86

simx86: add cache for FindTree

---

test/test_dos.py

This way a full diff is done for later checks which gives more information
in the logs.

test: move 5056-line check to first cpu test only

---

src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/trees.c

Since FindTree's cache hits are the most common case it's cheaper to move
the e_querymark checks past the cache check, just to avoid the more expensive
tree search if there is no code. The "first" check (from 431f6778) is not
worth the extra logic then.
This speeds up zx_emul by ~30%.

simx86: move e_querymark/InterOps checks past FindTree cache

---

test/common_framework.py
test/test_dos.py

I think this should do the trick. It shows elapsed time between start and stop of dosemu itself, not the build up and tear down of the test environment.

Travis ci 23

---

src/dosext/mfs/mfs.c

== Valgrind
==3930==  Uninitialised value was created by a stack allocation
==3930==    at 0x429AE0: SetRedirection (mfs.c:1712)
== Log file
MFS: Calculated DOS Information for 2:
MFS:   cwd=                 C:\
MFS:   cds flags = READY
MFS:   cdsfar = 0, 0

MFS: Don't print uninitialised variable

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/codegen-x86.h
src/base/emu-i386/simx86/interp.c

In the most common case (no debug output, no TSC usage, no FPU, no interrupt
inhibition and no trap flag use), the execution of generated code can be done
via a tight loop that checks for signals, finds the next node and checks for
links.
Execution zx_emul, this way Exec_x86 uses 12% instead of 20% of total execution
time and the total time drops by ~15%.

simx86: Exec_x86(): create fast inner loop

---

src/arch/linux/mapping/mapping.c
src/base/init/init.c
src/include/mapping.h

This fixes vm86+kvm_dpmi setup.

mapping: add MAPPING_NULL type

---

src/bindist/fdppauto.bat

This contains the line to introduce `dosrc.d`. Without a for loop for now due to limitations in comcom32.

Introduce dosrc.d, but comcom32 doesn't do for loops yet

---

test/common_framework.py
test/test_dos.py

1. Avoid testing on FreeDOS 1.20 due to the drive problem
2. libi86 updates
1. Checkout a known good version of libi86 (will need updating periodically) to test against
2. I made sure that on failure tkchia's log file is displayed and captured by travis. This purposefully broken run [here](https://travis-ci.com/github/andrewbird/dosemu2/builds/188173463) shows what you see in that event.

Travis ci 32

---

src/plugin/term/keyb_slang.c

This enables software (eg. wordperfect) that uses alt+function key shortcuts to work when run in terminal mode.

Add key mappings for alt-fn keys with slang

---

test/common_framework.py
test/test_dos.py

I added a little naive option handling and we gained the ability to list the DOS flavours plus the test names, and to finally be able to run the same test on all DOS flavours easily.
$ python3 test/test_dos.py --help
Usage: test/test_dos.py [--help | --list-cases | --list-tests] | [TestCase[.testname]]
$ python3 test/test_dos.py --list-cases
DRDOS701TestCase
FRDOS120TestCase
MSDOS622TestCase
PPDOSGITTestCase
$ python3 test/test_dos.py --list-tests
test_cpu_1_vm86native
test_cpu_2_jitnative
test_cpu_jit
test_cpu_jitkvm
test_cpu_kvm
test_cpu_kvmjit
test_cpu_kvmnative
< snip >
$ python3 test/test_dos.py DRDOS701TestCase.test_systype
< runs one specific test on one specific DOS type >
$ python3 test/test_dos.py DRDOS701TestCase
< runs all tests on DR-DOS >
$ python3 test/test_dos.py …

Travis: Make command line usage a little better

---

.travis.yml
test/common_framework.py
test/func_cpu_trap_flag.py
test/test_dos.py

Run as `python3 test/test_dos.py PPDOSGITTestCase.test_cpu_trap_flag`
1. Can you review my changes to your test case?
1. Can you check this fails on your system with current devel (should fail due to fixup message)?
2. Then if you roll back devel to before the 'fixup' commit, check that it still fails. (should fail due to incorrect value)?
Thanks!

Travis: Add cpu trap flag tests

---

test/common_framework.py
test/func_cpu_trap_flag.py
test/test_dos.py

1/ Allow tests to specify which and how many logs to display on
test failure.
2/ Change the display of our logs to occur after all tests have
been run rather than at individual test failure time. This is how
python unittest normally works and means that they are grouped
alongside any stdout or stderr that occured and the primary results
table is undisturbed on failure.
3/ Change the tests that use unusual logging practices to use the
new mechanism.

Travis: Log file handling

---

src/base/bios/x86/bios.s
src/dosext/mfs/lfn.c
src/dosext/mfs/mfs.c

In a forum post on DOS standards [1] the Enhanced DR-DOS
extension interrupt 21h service 7142h "long seek" was
mentioned [2]. There was a prior dosemu2 PR revision with
some discussion about it [3]. The changes since the first
revision include file size change detection as added to
the seek from EOF service too, and a change in how the
new and old style seeking interfaces are handled.
This commit makes mfs hook interrupt 21h service 7142h.
This new-style hook is handled to allow 64-bit seeking
with the same API as supported by Enhanced DR-DOS for
its FAT+ implementation.
The hook occurs in lfn.c and just passes the call to a
new interface, the redirector interrupt 2Fh service 1142h.
The handling is similar to that of service 71A6h. The
new redirector service is handled in mfs.c as usual. …

mfs: add 64-bit seek support, using EDR-DOS's int21.7142 [patch v2]

---

.github/workflows/ci-build.yml
.travis.yml

No need for this, as it's found automatically and creates an unnecessary
burden to change it when the kernel location changes.

Test: Don't override FDPP kernel placement

---

src/base/core/int.c
src/dosext/mfs/lfn.c
src/dosext/mfs/mfs.c

Much easier to deal with.
In lfn.c add a compatibility wrapper that adds / back.

mfs: remove trailing / on get redirection

---

src/plugin/dosdrv/umb.s
src/plugin/dosdrv/xms.inc

If there is no external himem, then there is no need to load
any driver. But the return code should still indicate success.

umb.sys: return success when not loading driver [#1512]

---

src/base/misc/disks.c
src/include/disks.h

See https://github.com/dosemu2/fdpp/discussions/178#discussioncomment-1094022
We do not have DMA boundary errors as we do not implement
the HDD driver, and all the drivers today use BM-DMA anyway.
So we need to tell the guest OS to not care about aligning
their buffers.
However, we still limit the transfer size to 64K max!
RBIL has this error code description:
09h    data boundary error (attempted DMA across 64K boundary or >80h sectors)
So I suppose the 64K limit should stay.

int13: set transparent DMA flag

---

src/dosext/mfs/mfs.h
src/include/dos2linux.h
src/plugin/debugger/mhpdbgc.c

The 16 bit address of the NUL device was incorrectly initialised
from a 32 bit variable, this seemed to work whilst the kernel was
in low memory, but after it moved up into upper things got broken.

dosdebug: Fix devs commands initialisation

---

src/dosext/dpmi/Makefile
src/dosext/dpmi/dnative.c
src/dosext/dpmi/dnative.h
src/dosext/dpmi/dpmi.c

We now have multiple DPMI backends, and only the native one
pollutes the main dpmi code, whereas it is least use.

dpmi: move native code to separate file

---

src/plugin/debugger/mhpdbgc.c

When loading a .MAP file, it's convenient to use a register as
the origin, for example:
dosdebug> usermap load-gnu test.map CS

Dosdebug: Allow usermap load* to take a register as origin

---

src/arch/linux/mapping/mapping.c
src/base/dev/vga/vgaemu.c
src/base/emu-i386/kvm.c
src/include/kvm.h
src/include/vgaemu.h

This is another attempt at avoiding the double page protection and TLBs being out of sync.
This uses the proper KVM api to track dirty pages. This way it is possible to do VGA dirty page tracking without needing to page fault into dosemu at all. I've also avoided needing an expensive syscall when back-switching VGA code tries to switch to the same bank it is already on.
I can confirm that micro machines and tristan pinball work fine with this patchset. I am not sure about Geos. @bolle732 could you test?
(Another working alternative I have is to completely use guest paging for everything -- in that case the assembly code in kvmmon.S will need to use invlpg or mov cr3 to invalidate the TLB.)

Kvm log dirty
