dosemu2/dosemu2

src/plugin/commands/commands.c

Separate branch and pull request for the changes pertaining to inbuilt commands uchdir / ugetcwd

Commands: Check return values on getcwd / chdir

---

src/plugin/commands/commands.c

Add more detail to failure message

Commands: Add error message detail

---

src/arch/linux/async/debug.c
src/arch/linux/mapping/mapfile.c
src/base/init/install.c
src/base/init/parser.y.in
src/base/misc/dos2linux.c
src/base/misc/fatfs.c
src/base/misc/utilities.c
src/plugin/X/X_font.c
src/plugin/commands/lredir.c
src/plugin/midimisc/mid_o_tmdty.c
src/tools/debugger/dosdebug.c
src/tools/debugger/mhpdbg.c

Reworked the malloc/asprintfs to assert() rather than the printf / return etcs in pull request #53. Also added similar code into the config parser yacc input.

Cleanups 02

---

src/plugin/commands/unix.c

#69 - add optional second param to unix -s to allow setting a different variable name.

unix.c - allow specifying the dos envvar name

---

src/base/async/dyndeb.c
src/base/async/int.c
src/base/misc/disks.c
src/base/misc/fatfs.c
src/dosext/mfs/mfs.c
src/emu-i386/kvm.c
src/include/int.h

Further development on the KVM branch.

Kvm (3rd PR)

---

src/arch/linux/mapping/mapping.c
src/emu-i386/kvm.c
src/emu-i386/kvmmon.S
src/include/mapping.h

This fixes vgaemu memory accesses and Windows 3.1.

Implement paging for vm86 in KVM and handle exceptions in _dosemu_fault.

---

src/emu-i386/simx86/cpatch.c
src/emu-i386/simx86/emu86.h
src/emu-i386/simx86/trees.c

Stas, first of all I hope you are doing better now and you can continue doing things. I see you have nevertheless been able to do some commits :)
I have some more changes to turn into PRs. This is the first. It fixes self-modifying code for cpuemu="full".
For vgaemu I will have some more fixes in other PRs. In the end it is best to use the cpatch code to apply to vgaemu as well.

Cpuemu full fix

---

etc/dosemu.conf
etc/global.conf
src/base/dev/vga/vgaemu.c
src/base/init/config.c
src/base/init/init.c
src/base/init/lexer.l.in
src/base/init/memcheck.c
src/base/init/parser.y.in
src/emu-i386/kvm.c
src/include/emu.h
src/include/kvm.h

As suggested in #104, $_umb_f0 + write-protect.

Simx86 prehistorik2 bugfix

---

src/base/misc/fatfs.c

There are no functional changes with this patch, its purpose is purely for
readablity.

fatfs: remove casts and calculated offsets

---

src/emu-i386/kvm.c

In the end commit 1c619289837 was not sufficient. With 256-color modes
both banked buffers and linear frame buffers alias the same VGA memory
and this confuses the page table machinery somewhere.

KVM: Retry KVM_RUN if it exits with EFAULT. Fixes #168.

---

src/bindist/loaddosinstall

Switch to the HTTPS URL for ibiblio

Use HTTPS for downloading instead of HTTP

---

src/base/init/install.c

Basically the menu you wrote about.
The terminology isn't great yet though...

Present a menu when system FreeDOS is available

---

src/base/misc/fatfs.c
src/tools/periph/mkfatimage16.c

1/ Set drive number on pre v3.40 bootblocks only where we have
a valid drive already, as it seems having the drive number defined
at offset 0x1fd is not as widespread as it first seemed.
2/ Be smarter in mkfatimage BPB modification of existing bootblocks.
This fixes FAT12/FAT16 image file boot with DR-DOS 3.40

disks: Be smarter with pre v3.40 bootblocks

---

src/base/video/remap.c

Remappers for converting 24/32-bit VESA mode to 32-bit X mode when running in fullscreen.
Support high colour VESA modes to 16/24-bit X modes has to come later.

Add remapper for 24/32-bit to 32-bit colours in fullscreen under X

---

src/base/misc/fatfs.c
src/env/commands/emufs.S

A couple of stand alone fixes that I found whilst doing the mfs work.

Drvfixes01

---

src/base/serial/fossil.c

Here's a first attempt at adding some additional X00 functions.
- How should I handle the Ctrl Break request (this is also an unimplemented FOSSIL function 0x0f)?
- I only tested with the socat method, but DN is now using the new function 0x1e without problems.

serial: Add some X00 functions to FOSSIL driver

---

src/tools/periph/mkfatimage16.c

When padding out to full filesize ensure that if in non raw mode we
allow for the header too.

mkfatimage: Calculate image filesize properly

---

src/base/misc/disks.c

Sorry, a small fix for the previous PR. Something I thought of later today.

fix maximum amount of CHS-addressable cylinders

---

src/base/async/int.c

1/ Handle the case where on DR-DOS the kernel program is run after first
loading it. DR-DOS uses a different subcommand (AL=0x80) and has no
command line, so don't try to add into the video title string.
2/ Let the program name be logged with ds_printf at all levels, it
doesn't happen very often and allows the code to appear neater.

int.c: Handle Program load/exec fully

---

src/base/init/parser.y

Since dosemu started supporting raw images, a disk header is not always
present. Remove the hardcoding of header size in parser, and allow the
log message to report the correct header size.

config: Don't assume all images have headers

---

src/tools/debugger/mhpdbgc.c

1/ Don't mix values with failure to parse
If the address didn't parse, let the caller know instead of
returning a valid address of 0.
2/ Check for invalid characters when looking up addresses
Prevents unknown symbols like 'fakefreddy' being resolved as
'00fa'address

dosdebug: Check for error when resolving addresses

---

src/base/misc/fatfs.c

This add initial boot support for PC-MOS. Tested with PC-MOS 5.01:
1/ Booting with type1, type2 and type9 disks.
2/ Booting with boot.blk and without
Note: There is a condition where booting fails with the message 'Command
processor cannot be found'. This is due to confusion of PC-MOS
disk numbering if no floppy drives are found on the system. This
occurs even when using an hdimage created by PC-MOS and it is
fully expected to occur on real hardware if the floppy drives are
disabled after the installation of PC-MOS onto the hard disk.
Dosemu will print an error to the console if PC-MOS is detected on
fatfs and no floppy drives are configured.

fatfs: Add boot support for PC-MOS [#502]

---

src/base/async/int.c

After converting long filenames to short filenames the LFN code remaps
the LFN Open call to use DOS's Extended open call 0x6c. Unfortunately
this was not present on MS-DOS & PC-DOS versions until v4.00 or on
DR-DOS until v7.00. If the DOS in use does not provide int21/6c this
patch provides a fall back to use int21/3c and int21/3d by using the
second revectoring facility. In the conversion of Extended open to
standard Create / Open calls some esoteric open bits are not supported,
such as synchronous writes, data compression and avoiding int24 on error.
Resolves #485 PR

lfn: Add fall back for DOS with missing int21/6c Open

---

src/emu-i386/do_vm86.c

Returning with VM86_STI without VIF is impossible with KVM or cpuemu.
In fact this is only possible with vm86() on kernels 4.3rc1+ since
kernel commit https://github.com/torvalds/linux/commit/5ed92a8ab71f

Move VM86_STI optimization from commit 11ae67fd to true_vm86().

---

src/dosext/dpmi/dpmi.c
src/dosext/dpmi/dpmi.h
src/tools/debugger/mhpdbgc.c

Tidy up for dosdebug's value processing mainly including fix for #616

Dosdebug 22

---

Makefile.conf.in
configure.ac
debian/control
dosemu2.spec.in
src/tools/debugger/Makefile
src/tools/debugger/dosdebug.c
src/tools/debugger/mhpdbgc.c

Very much a work in progress which does work mostly, but would you consider a PR later to add readline support for dosdebug?

Dosdebug 23

---

src/include/mhpdbg.h
src/tools/debugger/dosdebug.c
src/tools/debugger/mhpdbg.c
src/tools/debugger/mhpdbgc.c

Trace not quite right at the moment. See below

Dosdebug 25

---

src/base/misc/fatfs.c

Use a destinct filename for FDPP boot file. This allows us to do the
right thing if one is present and FDPP is not compiled in.
BTW is filename 'FDPPBOOT.SYS' okay?

fatfs: Define new system type for FDPP

---

src/dosext/mfs/mfs.c
src/dosext/mfs/mfs.h
src/env/builtins/builtins.c
src/env/builtins/builtins.h
src/env/builtins/lredir.c
src/env/builtins/system.c
src/include/redirect.h

Here's the first set of changes. Comments please?

Mfs fixes01c

---

src/dosext/mfs/lfn.c
src/dosext/mfs/mfs.c
src/dosext/mfs/mfs.h
src/env/builtins/builtins.c
src/include/redirect.h

For review, other commits to be added soon.

Mfs fixes01e

---

src/dosext/mfs/mfs.c

See https://github.com/stsp/dosemu2/issues/685 for the discussion.
[#685]

MFS: Don't assert on unknown redirector call

---

src/base/misc/fatfs.c

I started looking at #524, have you any ideas about where to put the MOS hack?

Bootsec 01

---

src/base/bios/Makefile
src/base/bios/bios.s

Builds an identical bios_data binary, just running tests at the moment, but of course I can squash into a single commit.

Biosunlink02

---

src/base/bios/bios.s
src/base/bios/hlt.c
src/dosext/mfs/lfn.c
src/dosext/mfs/mfs.c
src/include/bios.h
src/tools/debugger/mhpdbg.c

More trivial tidying. Please check 'global symbol 03' patch, I removed some casts that looked like they were left over from when we were diffing symbols for offsets.

Biosunlink03

---

src/plugin/debugger/Makefile
src/plugin/debugger/Makefile.conf.in
src/plugin/debugger/configure.ac

I think this could be useful, what do you think?

Dosdebug 32

---

src/base/bios/x86/bios.s

Refer to https://github.com/stsp/dosemu2/issues/770#issuecomment-462077485

bios.s: clc in int_rvc after shifts

---

src/base/misc/fatfs.c

Trivial tweak to logging, no functional change.

fatfs: Only log system type if found

---

src/plugin/debugger/mhpdbgc.c

~~~
dosdebug> mcbs
dosdebug>
ADDR      PARAS  OWNER
0284:0000 0x0020 [DOS]
02a5:0000 END
ADDR(UMA) PARAS  OWNER
9fff:0000 0x2300 [DOS]
c300:0000 0x0130 [DOS]
c431:0000 0x0006 [FREE]
c438:0000 0x12c1 [COMMAND]
d6fa:0000 0x0904 [FREE]
dfff:0000 0x1000 [DOS]
f000:0000 0x0513 [FREE]
f514:0000 0x0619 [COMMAND]
fb2e:0000 0x0090 [COMMAND]
fbbf:0000 END(UMA)
~~~

dosdebug: Add display of UMBs to MCBs command

---

src/dosext/builtins/builtins.c

Change check to test for existence those physical drives that are
present but unformatted.
- one fatfs virtual disk
- two image disks with multiple primary partitions
- one image disk with one unformatted primary partition, an
extended partition, and an unformatted logical partition.
- three automatic fatfs virtual disks
$_hdimage = "dXXXXs/c:hdtype1 dXXXXs/hard1.img dXXXXs/hard2.img"
"dXXXXs/unformatted.img +1"
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD2, Pri[ 1], CHS=    0-32-33, start=     1 MB, size=    12 MB
E: HD3, Pri[ 1], CHS=    0-32-33, start=     1 MB, size=    12 MB
F: HD4, Pri[ 1], CHS=    0-32-33, start=     1 MB, size=     5 MB
G: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
H: HD6, Pri[ 1], CHS=    0-1-1, start=     0 MB, size= …

lredir: Ask DOS if drive is free [fixes #768]

---

src/plugin/debugger/dosdebug.c
src/plugin/debugger/mhpdbg.c
src/plugin/debugger/mhpdbgc.c

1/ Small tidy up
2/ Add `usermap search <prior|nearest> [ADDR]` subcommand
3/ Add `symbol` synonym

Dosdebug 42

---

.travis.yml
test/test_dos.py
travis_prereq.sh
travis_test.sh

Add another 16 tests now that we have DJGPP compiler available.

Travis ci 02

---

.travis.yml
test/test_dos.py
travis_prereq.sh
travis_test.sh

Add FreeDOS 1.20 into the test regime,TestCase specific skipping and FCB read/write tests.

Travis ci 04

---

test/test_dos.py

Testing tidyups and a new test

Travis ci 06

---

test/common_framework.py
test/test_dos.py
travis_test.sh

1/ Code shuffling to share the common parts of the test suite
2/ Make the CPUEMU tests build on 32 and 64 bit machines
3/ Carve up the CPUEMU tests so that we can run single tests
4/ Add CPUEMU test to run on Dosemu with only FDPP
Six tests failing, some diffs because of mismatch in addresses etc.

Travis ci 07

---

src/dosext/mfs/lfn.c
src/dosext/mfs/mfs.c

Minor tweaks to MFS/LFN logging

Mfs fixes03

---

test/test_dos.py

Add a little infrastructure + FCBDelete / FCBFind tests.

Travis ci 08

---

src/plugin/debugger/dosdebug.c

1/ Readline now saves current command line content and position before
erasing. Then the incoming response is displayed and afterwards the
maybe partial command line content and position is restored.
2/ Both the non-readline and readline versions now print the newline
after the response to better delineate the respective command / response
pairs.

dosdebug: Fixup command / response display

---

.travis.yml
test/common_framework.py
test/test_dos.py

New tests for LFN support return values so that we don't silently break it again.

Travis: More tests and tidy ups

---

src/base/kbd_unicode/keymaps.c

All I have time for at the moment

Keymap euro

---

test/test_dos.py

Start two FindFirst (one wild, one plain) with different DTAs,
then check we get a proper result with FindNext using the first
DTA. See PR #1010
Thanks to @bartoldeman for the skeleton test in NASM

Travis: Add DOS v2 FindFirst/FindNext mixed DTA tests

---

src/arch/linux/mapping/mapping.c

This uses a runtime version check so that the code is backwards compatible
if ran on older kernels for which MAP_FIXED_NOREPLACE is a no-op.

Only assert MAP_FIXED_NOREPLACE for kernel>=4.17

---

src/arch/linux/async/sigsegv.c

This relates to #620 and #1020 as the only linear address that comes out
of vm86 is cr2 so we want to make that case isolated.

Cleanup dosemu_fault1: consolidate CPUEMU, isolate vm86().

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/fp87-sim.c
src/base/emu-i386/simx86/interp.c
test/test_dos.py

These patches fix the remaining  issues with fullsim and enable the test in Travis.

Fix cpusim test

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/sigsegv.c

Next one from #156 (last string instruction replaced).

Replace lods without rep.

---

test/common_framework.py
test/test_dos.py
travis_test.sh

Travis ci 13

---

test/test_dos.py

1/ Get ftime
Note: we need to split this test as FAT cannot have enough files
in the root directory for the whole test, and mkimage can't
store them in a subdirectory.
2/ Set ftime
Written to perform similar pattern as test 2-B in the locking test
at http://www.burtonsys.com/download/TESTLOCK.ZIP but without the
seconds field out of range bug that makes its results somewhat random.
The whole range of valid values for each field is tested, whereas the
original just calculated a single new date/time based on the current
date/time.
Note: out of valid range values are not tested; on FAT they would
be passed through to DOS and stored on disk unchanged; on MFS they
would be adjusted within the redirector to be in range as there is
no sensible way of storing and retrieving them within the Unix …

Travis: add get / set filetime tests

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/sigsegv.c
src/base/misc/dos2linux.c
src/include/dos2linux.h

The read_* functions are in dos2linux.c just like the write_* functions.
e_VgaRead() has been eliminated.

simx86: introduce read_byte/word/dword, use in sim mode.

---

test/test_dos.py

Note: MFS test disabled for now

Travis: add lock file twice test

---

src/base/dev/vga/vgaemu.c

Change vga_read_access/vga_write_access as follows:
* return 0 for r/w dirty pages as they can quickly be written to using
WRITE_BYTE etc, and in simx86 sim mode they are added to the unprotected
page cache.
* return 1 for r/o pages in the LFB and let vga_mark_dirty handle those
so simx86 no longer faults on those in sim mode.
* use vgaemu_prot_ok with its cache instead of explicit limits.
* to deal with optional UMBs at 0xa0000 and 0xb0000 just keep a permanent
R/W setting in the prot cache so vga_read/write_access always return 0
for those.
* e_invalidate_full is now called when the vga prot_cache is also updated.
I checked various games and fractint in sim mode and all works well and
faster than before.

vgaemu: vga_read/write_access to work w/LFB & quick dirty access.

---

src/base/misc/dos2linux.c

Fixes a regression from 43ac821

read_*: only add writable pages to the cache. Fixes #1100.

---

src/base/dev/vga/vgaemu.c

Only keep the parts that check for memory ranges, to deal with the LFB in
vga_read/write_access and vga_mark_dirty.

Revert parts of 9be5b9b, because of potential for thread races.

---

src/base/dev/vga/vgaemu.c
src/base/emu-i386/simx86/cpatch.c

This is a minimal followup to #1105 that really does not unprotect VGA memory.
vga_write and related functions instead dirty the page(s) and then write directly
to vga.mem.base which is always unprotected.

simx86: never unprotect VGA memory (#1105)

---

src/base/dev/vga/vgaemu.c

Since the offset into vga.mem.base is already calculated vga_mark_dirty() can
use that. Also let it lock as in the vgacpy branch.

vgaemu: simplify vga_mark_dirty()

---

src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/trees.c

This fixes various bugs I've found while
chasing down #86. Which is still not fixed.

some jit fixes

---

src/base/emu-i386/simx86/interp.c

The issue with call far seg:ofs in sim mode is that CS is immediately set to
the new value but JumpGen still expected the old value, and pushed the
wrong return address. Fix this by generating everything in JumpGen and by
making it remember the old CS base.

simx86: fix sim mode regression from a1174847

---

src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/interp.c

Handling non-revectored INTs in Interp86 is a little faster than outside the
loop, though eventually they should be compiled.
This also makes sure that revectored ints always cause #GP(0), they should not
set an error code unlike protected mode ints.

simx86: move v86 handling of non-revectored INTxx to Interp86.

---

src/base/emu-i386/simx86/interp.c

Looks more like a pre-existing bug: the "near" condition
in SIM mode was checked with the silly "same page" check,
((P2 ^ j_t) & PAGE_MASK)==0
Refactor that code a bit to also remove not that silly but
still strange BT24 checks.

interp: fix JumpGen regression of 507e05f

---

src/base/emu-i386/simx86/codegen-sim.c
src/base/emu-i386/simx86/codegen-x86.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/interp.c

This allows the use of symbolic constants and merging some indentical fragments.

simx86: JumpGen: replace cond code with opc (opcode)

---

test/common_framework.py
test/test_dos.py

For discussion with fdpp share issue.

Travis: Add share delete/rename test

---

etc/dosemu.conf

Information for beginners: drive letter mapping, and PostScript output required for PDF.

More explanations in dosemu.conf

---

src/plugin/debugger/dis8086.c

First is https://github.com/dosemu2/dosemu2/issues/1165
Second is https://github.com/dosemu2/dosemu2/issues/1166

ecm disasm fixes

---

src/base/init/config.c

Adds the -Y switch to the option list in the help screen.

Display -Y switch

---

test/test_dos.py

Since commit af296b8 this is supported so it should be tested too.

Tests: test JIT/sim vm86 + KVM DPMI

---

travis_build.sh
travis_test.sh

PR #1211 failed "configure" but Travis reported it ok when it should have
failed.

test: use "set -e" in travis script to make it fail when any step fails.

---

src/base/emu-i386/simx86/memory.c

e_querymark was very slow for high values of len since it checked bit by bit.
Checking uint64_t's with masks if needed is much faster.
I checked logs for "QUERY MARK found code at" to double check correctness.
e_markpage and e_unmarkpage can be sped up the same way, but I'll leave that
for another PR. They are not called as often.

simx86: speed up e_querymark for len>1

---

src/base/emu-i386/simx86/codegen-x86.c

The node linker was checking for inside links (which usually means tight loops)
every time a node was executed, whereas this is only needed when the node is created.
This speeds up zx_emul by another second (from 15 to 14).

simx86: nodelinker: check inside links only at node creation

---

test/common_framework.py
test/test_dos.py

Should fix the freedos tests after rename of autoexec.bat.

Travis ci 20

---

.travis.yml
test/common_framework.py
test/test_dos.py
travis_test.sh

Hopefully you should see here that the full gamut of tests is done, whereas in my topic branch only fdpp was.

Travis ci 24

---

travis_test.sh

With this commit the following should apply:
When                        | When
----------------------------| ---------------
Topic branch                | fdpp
Devel and PR merge to devel | fdpp + msdos
Cron job of devel           | fdpp + msdos + freedos + drdos + ...
To setup the cron job, the repo owner (@stsp) will have to configure it in the Travis UI, see https://docs.travis-ci.com/user/cron-jobs/

Travis: Introduce a 3rd class of test 'cron'

---

src/arch/linux/async/sigsegv.c
src/base/emu-i386/cpu.c
src/base/emu-i386/kvm.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/emu86.h
src/base/emu-i386/simx86/interp.c
src/base/emu-i386/simx86/memory.c
src/base/emu-i386/simx86/sigsegv.c
src/dosext/dpmi/emu-ldt.c
src/include/cpu-emu.h
test/test_dos.py

This is an unusual case but still worth testing for edge cases.

test: test kvm vm86 + emulated (JIT/sim) DPMI

---

test/common_framework.py

1/ Use new commands location
2/ Add new /bat directory
3/ Remove --libdir as it's now automatic

Travis: Update to new layout

---

src/base/core/int.c
src/dosext/builtins/system.c
src/dosext/mfs/lfn.c
src/dosext/mfs/mangle.c
src/dosext/mfs/mfs.c
src/dosext/net/libpacket.c
src/plugin/debugger/mhpdbgc.c
src/plugin/fdpp/fdpp.c
src/plugin/periph/mkfatimage16.c

First chunk of Coverity fixes, mostly classified Low risk.

Coverity 01

---

src/arch/linux/mapping/mapping.c
src/base/core/int.c
src/base/core/priv.c
src/base/dev/pic/pic.c
src/base/misc/disks.c
src/base/video/video.c
src/dosext/dpmi/dpmi.c
src/dosext/mfs/lfn.c
src/dosext/net/libpacket.c
src/plugin/console/detach.c
src/plugin/term/keyb_slang.c

Second chunk of Coverity fixes. Could you please review carefully the switch/missing break fixes as they are open to interpretation?

Coverity 02

---

src/arch/linux/mapping/mapfile.c
src/base/video/instremu.c
src/dosext/net/libpacket.c
src/dosext/net/pktnew.c
src/plugin/debugger/dosdebug.c

Third slice of coverity fixes.

Coverity 03

---

src/arch/linux/mapping/mapping.c
src/base/serial/tty_io.c
src/dosext/mfs/lfn.c
src/dosext/mfs/mfs.c
src/dosext/mfs/util.c
src/plugin/midimisc/mid_o_pipe.c
src/plugin/midimisc/mid_o_tmdty.c

For discussion, in particular VFAT directory, LFN delete

Coverity 04

---

.travis.yml
src/dosext/dpmi/dpmi.c
test/common_framework.py
test/ecm/dpmitest/Makefile
test/ecm/dpmitest/dpmialoc.asm
test/ecm/dpmitest/dpmimini.asm
test/ecm/dpmitest/dpmims.asm
test/ecm/dpmitest/dpmipsp.asm
test/ecm/lmacros/jn_warn.mac
test/ecm/lmacros/lmacros1.mac
test/ecm/lmacros/lmacros2.mac
test/ecm/lmacros/lmacros3.mac
test/test_dos.py
travis_test.sh

Next chunk of tests, mainly covering memory.

Travis ci 29

---

src/base/emu-i386/cputime.c
src/base/init/config.c
src/base/misc/disks.c
src/base/misc/fatfs.c
src/dosext/mfs/mfs.c
src/dosext/net/pktnew.c
src/plugin/debugger/dis8086.c
src/plugin/sdl/sdl.c

Coverity 05

---

src/base/misc/disks.c
src/base/misc/ioctl.c
src/base/misc/utilities.c
src/base/mouse/mouseint.c
src/dosext/mfs/mfs.c
src/dosext/net/libpacket.c
src/plugin/X/X_font.c
src/plugin/gpm/mouse_gpm.c
src/plugin/periph/hdinfo.c
src/plugin/periph/mkhdimage.c
src/plugin/term/keyb_slang.c

Coverity 06

---

test/common_framework.py
test/test_dos.py

Trivial and cosmetic changes only

Travis ci 33

---

src/base/misc/disks.c

- update different BDA location for operation status,
depending on whether it is a floppy disk or hard
disk operation
- for non-existent floppy, return 80h in both AH and
BDA, rather than inconsistent error codes
- AH = 01h should actually return the status of the
last operation (!), and return it in AH

int13: further fixes for issue #1295

---

test/func_ds2_set_fattrs.py
test/func_ds3_share_open_access.py
test/test_dos.py

Travis ci 38

---

test/func_ds3_lock_readonly.py
test/test_dos.py

Disable our tests that need setfattr to work.

Travis ci 41

---

test/func_ds3_lock_two_handles.py
test/test_dos.py

Travis ci 42

---

src/dosext/builtins/xmode.c

Trivial tidy up commit I've had kicking around for a while

builtins: Make xmode use constants from video.h

---

src/plugin/sdl/sdl.c

If not using bitmap text, then X_plugin is used instead.

SDL: Remove unused X text stuff

---

etc/dosemu.conf
etc/global.conf
src/arch/linux/async/signal.c
src/arch/linux/async/sigsegv.c
src/base/core/emu.c
src/base/core/int.c
src/base/emu-i386/cpu.c
src/base/emu-i386/simx86/cpu-emu.c
src/base/emu-i386/simx86/trees.c
src/base/init/config.c
src/base/init/init.c
src/base/init/lexer.l
src/base/init/parser.y
src/base/misc/mmio_tracing.c
src/dosext/dpmi/dpmi.c
src/include/emu.h
src/plugin/debugger/mhpdbgc.c
test/test_dos.py

It now accepts "jit" or "sim".

rework $_cpu_emu option [fixes #1361]

---

.travis.yml
test/common_framework.py
test/func_cpu_trap_flag.py
test/func_ds2_file_seek_read.py
test/func_ds2_file_seek_tell.py
test/func_ds2_set_fattrs.py
test/func_ds3_lock_readlckd.py
test/func_ds3_lock_readonly.py
test/func_ds3_lock_twice.py
test/func_ds3_lock_two_handles.py
test/func_ds3_lock_writable.py
test/func_ds3_share_open_access.py
test/func_ds3_share_open_twice.py
test/func_lfs_file_info.py
test/func_lfs_file_seek_tell.py
test/test_dos.py

A few updates here:
- The long overdue switch to testing on Focal
- A precursor to my being able to test any future DOS file attributes patch that needs xattrs, is the switch to support a test directory outside of the build
- New test for ECM's int21/7142 64 bit seek on MFS

Travis ci 45

---

test/common_framework.py
test/func_lfs_file_seek_tell.py
test/test_dos.py

Some tweaks that had been sitting here for a while

Travis ci 46

---

.github/workflows/ci-build.yml
.travis.yml
ci_build.sh
ci_prereq.sh
ci_test.sh
test/func_ds3_lock_concurrent.py
test/test_dos.py

Since Travis still haven't got back to me regarding the OSS credits, I think we should apply this to add github actions support.
Notes:
1/ there is no KVM support on Github Actions, so tests requiring KVM are skipped as all testing is done with emulation
2/ a test is currently failing (it's only recently turned that way, four days ago it was okay), anyway it's not all bad as it gave me a chance to add the failure logs as an artifact you can download from Github. That's something you can't do on Travis!

Travis ci 47

---

test/test_dos.py

Test: Update expected response from lredir

---

ci_prereq.sh

Hopefully this will stop travis hanging

Test: apt defaults seem to be different on Travis

---

.travis.yml

Test: avoid testing with broken apt install on Travis

---

src/plugin/debugger/mhpdbgc.c

Fixes for dosdebug discussed in comments on https://github.com/dosemu2/fdpp/commit/9d107daaf43a6b41f9f1a2aefd2c6279499172e4

Dosdebug 49

---

ci_test.sh
test/test_dos.py

Since Travis test time is finite, limit tests there to just CPU ones.

CI: On Travis just do cputests

---

ci_test.sh
test/func_cpu_trap_flag.py
test/test_dos.py

Some little tidyups and a couple of new tests.

Ci newtests 01

---

src/base/bios/int16.c
src/base/core/coopth.c
src/base/core/int.c
src/base/emu-i386/cputime.c
src/dosext/builtins/commands.c
src/dosext/dpmi/dpmi.c
src/dosext/dpmi/msdoshlp.c
src/dosext/net/ipx.c
src/include/cpu.h
src/include/timers.h

See https://github.com/dosemu2/dosemu2/commit/8284d58d3bd1970454a66cef3db4dd3350375b2a

coopth: allow small sleeps with ints disabled
